window.DAYTYPE_DATA = {
 "built_note": "15m bars, 60d fetch; last 21 sessions = eval window",
 "n": 140,
 "tradeable_path_pct": 10.0,
 "unusual_note": "unusual_pct = % of eval sessions with path >= 1.5x own trailing ~60d median path; separate signal, feeds no label",
 "rows": [
  {
   "ticker": "INFQ",
   "n_days": 21,
   "avg_eff": 0.323,
   "pct_trend": 38.1,
   "pct_chop": 38.1,
   "pct_mixed": 23.8,
   "avg_path_pct": 8.3,
   "avg_range_pct": 4.6,
   "avg_largest_swing_pct": 4.5,
   "tradeable_pct": 33.3,
   "unusual_pct": 0.0,
   "character": "BALANCED"
  },
  {
   "ticker": "IREN",
   "n_days": 21,
   "avg_eff": 0.526,
   "pct_trend": 61.9,
   "pct_chop": 33.3,
   "pct_mixed": 4.8,
   "avg_path_pct": 7.9,
   "avg_range_pct": 5.2,
   "avg_largest_swing_pct": 5.0,
   "tradeable_pct": 23.8,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "SMR",
   "n_days": 21,
   "avg_eff": 0.469,
   "pct_trend": 61.9,
   "pct_chop": 23.8,
   "pct_mixed": 14.3,
   "avg_path_pct": 7.8,
   "avg_range_pct": 5.4,
   "avg_largest_swing_pct": 5.2,
   "tradeable_pct": 28.6,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "RGTI",
   "n_days": 21,
   "avg_eff": 0.403,
   "pct_trend": 42.9,
   "pct_chop": 33.3,
   "pct_mixed": 23.8,
   "avg_path_pct": 7.7,
   "avg_range_pct": 4.3,
   "avg_largest_swing_pct": 3.9,
   "tradeable_pct": 19.0,
   "unusual_pct": 9.5,
   "character": "QUIET"
  },
  {
   "ticker": "LPTH",
   "n_days": 21,
   "avg_eff": 0.383,
   "pct_trend": 42.9,
   "pct_chop": 42.9,
   "pct_mixed": 14.3,
   "avg_path_pct": 7.6,
   "avg_range_pct": 4.9,
   "avg_largest_swing_pct": 4.6,
   "tradeable_pct": 19.0,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "BE",
   "n_days": 21,
   "avg_eff": 0.488,
   "pct_trend": 47.6,
   "pct_chop": 19.0,
   "pct_mixed": 33.3,
   "avg_path_pct": 7.4,
   "avg_range_pct": 4.6,
   "avg_largest_swing_pct": 4.2,
   "tradeable_pct": 19.0,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "NBIS",
   "n_days": 21,
   "avg_eff": 0.495,
   "pct_trend": 47.6,
   "pct_chop": 33.3,
   "pct_mixed": 19.0,
   "avg_path_pct": 7.2,
   "avg_range_pct": 4.2,
   "avg_largest_swing_pct": 3.9,
   "tradeable_pct": 23.8,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "SNDK",
   "n_days": 21,
   "avg_eff": 0.443,
   "pct_trend": 52.4,
   "pct_chop": 19.0,
   "pct_mixed": 28.6,
   "avg_path_pct": 7.1,
   "avg_range_pct": 4.7,
   "avg_largest_swing_pct": 4.4,
   "tradeable_pct": 19.0,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "CTMX",
   "n_days": 21,
   "avg_eff": 0.531,
   "pct_trend": 47.6,
   "pct_chop": 9.5,
   "pct_mixed": 42.9,
   "avg_path_pct": 7.0,
   "avg_range_pct": 4.7,
   "avg_largest_swing_pct": 4.4,
   "tradeable_pct": 23.8,
   "unusual_pct": 38.1,
   "character": "QUIET"
  },
  {
   "ticker": "OKLO",
   "n_days": 21,
   "avg_eff": 0.381,
   "pct_trend": 33.3,
   "pct_chop": 19.0,
   "pct_mixed": 47.6,
   "avg_path_pct": 6.9,
   "avg_range_pct": 4.3,
   "avg_largest_swing_pct": 4.1,
   "tradeable_pct": 14.3,
   "unusual_pct": 14.3,
   "character": "QUIET"
  },
  {
   "ticker": "COIN",
   "n_days": 21,
   "avg_eff": 0.511,
   "pct_trend": 66.7,
   "pct_chop": 14.3,
   "pct_mixed": 19.0,
   "avg_path_pct": 6.7,
   "avg_range_pct": 4.7,
   "avg_largest_swing_pct": 4.4,
   "tradeable_pct": 14.3,
   "unusual_pct": 14.3,
   "character": "QUIET"
  },
  {
   "ticker": "CBRS",
   "n_days": 21,
   "avg_eff": 0.469,
   "pct_trend": 47.6,
   "pct_chop": 33.3,
   "pct_mixed": 19.0,
   "avg_path_pct": 6.6,
   "avg_range_pct": 3.7,
   "avg_largest_swing_pct": 3.4,
   "tradeable_pct": 23.8,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "SMCI",
   "n_days": 21,
   "avg_eff": 0.483,
   "pct_trend": 47.6,
   "pct_chop": 28.6,
   "pct_mixed": 23.8,
   "avg_path_pct": 6.5,
   "avg_range_pct": 4.1,
   "avg_largest_swing_pct": 3.9,
   "tradeable_pct": 14.3,
   "unusual_pct": 9.5,
   "character": "QUIET"
  },
  {
   "ticker": "IONQ",
   "n_days": 21,
   "avg_eff": 0.393,
   "pct_trend": 33.3,
   "pct_chop": 38.1,
   "pct_mixed": 28.6,
   "avg_path_pct": 6.4,
   "avg_range_pct": 3.8,
   "avg_largest_swing_pct": 3.5,
   "tradeable_pct": 9.5,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "CRWV",
   "n_days": 21,
   "avg_eff": 0.552,
   "pct_trend": 52.4,
   "pct_chop": 28.6,
   "pct_mixed": 19.0,
   "avg_path_pct": 6.0,
   "avg_range_pct": 4.1,
   "avg_largest_swing_pct": 3.9,
   "tradeable_pct": 9.5,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "SOUN",
   "n_days": 21,
   "avg_eff": 0.484,
   "pct_trend": 66.7,
   "pct_chop": 19.0,
   "pct_mixed": 14.3,
   "avg_path_pct": 6.0,
   "avg_range_pct": 4.0,
   "avg_largest_swing_pct": 3.5,
   "tradeable_pct": 9.5,
   "unusual_pct": 19.0,
   "character": "QUIET"
  },
  {
   "ticker": "STX",
   "n_days": 21,
   "avg_eff": 0.371,
   "pct_trend": 38.1,
   "pct_chop": 38.1,
   "pct_mixed": 23.8,
   "avg_path_pct": 5.9,
   "avg_range_pct": 3.5,
   "avg_largest_swing_pct": 3.2,
   "tradeable_pct": 4.8,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "MRVL",
   "n_days": 21,
   "avg_eff": 0.461,
   "pct_trend": 42.9,
   "pct_chop": 38.1,
   "pct_mixed": 19.0,
   "avg_path_pct": 5.8,
   "avg_range_pct": 3.5,
   "avg_largest_swing_pct": 3.3,
   "tradeable_pct": 9.5,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "AVAV",
   "n_days": 21,
   "avg_eff": 0.545,
   "pct_trend": 57.1,
   "pct_chop": 33.3,
   "pct_mixed": 9.5,
   "avg_path_pct": 5.8,
   "avg_range_pct": 4.0,
   "avg_largest_swing_pct": 3.8,
   "tradeable_pct": 14.3,
   "unusual_pct": 14.3,
   "character": "QUIET"
  },
  {
   "ticker": "QBTS",
   "n_days": 21,
   "avg_eff": 0.439,
   "pct_trend": 42.9,
   "pct_chop": 33.3,
   "pct_mixed": 23.8,
   "avg_path_pct": 5.8,
   "avg_range_pct": 3.6,
   "avg_largest_swing_pct": 3.3,
   "tradeable_pct": 4.8,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "ASTS",
   "n_days": 21,
   "avg_eff": 0.466,
   "pct_trend": 47.6,
   "pct_chop": 28.6,
   "pct_mixed": 23.8,
   "avg_path_pct": 5.8,
   "avg_range_pct": 3.7,
   "avg_largest_swing_pct": 3.5,
   "tradeable_pct": 9.5,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "ONDS",
   "n_days": 21,
   "avg_eff": 0.474,
   "pct_trend": 47.6,
   "pct_chop": 38.1,
   "pct_mixed": 14.3,
   "avg_path_pct": 5.8,
   "avg_range_pct": 3.9,
   "avg_largest_swing_pct": 3.6,
   "tradeable_pct": 9.5,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "HOOD",
   "n_days": 21,
   "avg_eff": 0.59,
   "pct_trend": 66.7,
   "pct_chop": 14.3,
   "pct_mixed": 19.0,
   "avg_path_pct": 5.6,
   "avg_range_pct": 4.0,
   "avg_largest_swing_pct": 3.7,
   "tradeable_pct": 9.5,
   "unusual_pct": 9.5,
   "character": "QUIET"
  },
  {
   "ticker": "IOT",
   "n_days": 21,
   "avg_eff": 0.564,
   "pct_trend": 47.6,
   "pct_chop": 14.3,
   "pct_mixed": 38.1,
   "avg_path_pct": 5.5,
   "avg_range_pct": 3.7,
   "avg_largest_swing_pct": 3.4,
   "tradeable_pct": 4.8,
   "unusual_pct": 28.6,
   "character": "QUIET"
  },
  {
   "ticker": "DELL",
   "n_days": 21,
   "avg_eff": 0.624,
   "pct_trend": 66.7,
   "pct_chop": 23.8,
   "pct_mixed": 9.5,
   "avg_path_pct": 5.5,
   "avg_range_pct": 4.1,
   "avg_largest_swing_pct": 3.9,
   "tradeable_pct": 9.5,
   "unusual_pct": 14.3,
   "character": "QUIET"
  },
  {
   "ticker": "AXON",
   "n_days": 21,
   "avg_eff": 0.576,
   "pct_trend": 66.7,
   "pct_chop": 14.3,
   "pct_mixed": 19.0,
   "avg_path_pct": 5.5,
   "avg_range_pct": 4.1,
   "avg_largest_swing_pct": 3.9,
   "tradeable_pct": 9.5,
   "unusual_pct": 23.8,
   "character": "QUIET"
  },
  {
   "ticker": "PCT",
   "n_days": 21,
   "avg_eff": 0.398,
   "pct_trend": 33.3,
   "pct_chop": 47.6,
   "pct_mixed": 19.0,
   "avg_path_pct": 5.5,
   "avg_range_pct": 3.8,
   "avg_largest_swing_pct": 3.4,
   "tradeable_pct": 4.8,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "INOD",
   "n_days": 21,
   "avg_eff": 0.541,
   "pct_trend": 52.4,
   "pct_chop": 14.3,
   "pct_mixed": 33.3,
   "avg_path_pct": 5.4,
   "avg_range_pct": 3.6,
   "avg_largest_swing_pct": 3.5,
   "tradeable_pct": 9.5,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "ARM",
   "n_days": 21,
   "avg_eff": 0.508,
   "pct_trend": 52.4,
   "pct_chop": 19.0,
   "pct_mixed": 28.6,
   "avg_path_pct": 5.3,
   "avg_range_pct": 3.9,
   "avg_largest_swing_pct": 3.6,
   "tradeable_pct": 4.8,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "RDDT",
   "n_days": 21,
   "avg_eff": 0.515,
   "pct_trend": 57.1,
   "pct_chop": 19.0,
   "pct_mixed": 23.8,
   "avg_path_pct": 5.2,
   "avg_range_pct": 3.6,
   "avg_largest_swing_pct": 3.4,
   "tradeable_pct": 0.0,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "OKTA",
   "n_days": 21,
   "avg_eff": 0.493,
   "pct_trend": 52.4,
   "pct_chop": 14.3,
   "pct_mixed": 33.3,
   "avg_path_pct": 5.1,
   "avg_range_pct": 3.8,
   "avg_largest_swing_pct": 3.6,
   "tradeable_pct": 0.0,
   "unusual_pct": 9.5,
   "character": "QUIET"
  },
  {
   "ticker": "KTOS",
   "n_days": 21,
   "avg_eff": 0.501,
   "pct_trend": 52.4,
   "pct_chop": 23.8,
   "pct_mixed": 23.8,
   "avg_path_pct": 5.1,
   "avg_range_pct": 3.2,
   "avg_largest_swing_pct": 3.1,
   "tradeable_pct": 4.8,
   "unusual_pct": 9.5,
   "character": "QUIET"
  },
  {
   "ticker": "SPCX",
   "n_days": 21,
   "avg_eff": 0.451,
   "pct_trend": 42.9,
   "pct_chop": 19.0,
   "pct_mixed": 38.1,
   "avg_path_pct": 5.1,
   "avg_range_pct": 3.5,
   "avg_largest_swing_pct": 3.3,
   "tradeable_pct": 4.8,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "WDC",
   "n_days": 21,
   "avg_eff": 0.402,
   "pct_trend": 38.1,
   "pct_chop": 19.0,
   "pct_mixed": 42.9,
   "avg_path_pct": 5.0,
   "avg_range_pct": 3.2,
   "avg_largest_swing_pct": 2.9,
   "tradeable_pct": 9.5,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "RBLX",
   "n_days": 21,
   "avg_eff": 0.537,
   "pct_trend": 57.1,
   "pct_chop": 14.3,
   "pct_mixed": 28.6,
   "avg_path_pct": 4.9,
   "avg_range_pct": 3.6,
   "avg_largest_swing_pct": 3.3,
   "tradeable_pct": 4.8,
   "unusual_pct": 9.5,
   "character": "QUIET"
  },
  {
   "ticker": "HPE",
   "n_days": 21,
   "avg_eff": 0.654,
   "pct_trend": 81.0,
   "pct_chop": 9.5,
   "pct_mixed": 9.5,
   "avg_path_pct": 4.8,
   "avg_range_pct": 4.0,
   "avg_largest_swing_pct": 3.7,
   "tradeable_pct": 4.8,
   "unusual_pct": 14.3,
   "character": "QUIET"
  },
  {
   "ticker": "TSEM",
   "n_days": 21,
   "avg_eff": 0.398,
   "pct_trend": 33.3,
   "pct_chop": 47.6,
   "pct_mixed": 19.0,
   "avg_path_pct": 4.8,
   "avg_range_pct": 3.3,
   "avg_largest_swing_pct": 3.0,
   "tradeable_pct": 0.0,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "RKLB",
   "n_days": 21,
   "avg_eff": 0.477,
   "pct_trend": 47.6,
   "pct_chop": 38.1,
   "pct_mixed": 14.3,
   "avg_path_pct": 4.8,
   "avg_range_pct": 3.2,
   "avg_largest_swing_pct": 2.8,
   "tradeable_pct": 9.5,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "LASR",
   "n_days": 21,
   "avg_eff": 0.513,
   "pct_trend": 52.4,
   "pct_chop": 28.6,
   "pct_mixed": 19.0,
   "avg_path_pct": 4.8,
   "avg_range_pct": 3.3,
   "avg_largest_swing_pct": 3.1,
   "tradeable_pct": 4.8,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "ON",
   "n_days": 21,
   "avg_eff": 0.515,
   "pct_trend": 61.9,
   "pct_chop": 14.3,
   "pct_mixed": 23.8,
   "avg_path_pct": 4.6,
   "avg_range_pct": 3.2,
   "avg_largest_swing_pct": 3.1,
   "tradeable_pct": 4.8,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "CVNA",
   "n_days": 21,
   "avg_eff": 0.624,
   "pct_trend": 76.2,
   "pct_chop": 14.3,
   "pct_mixed": 9.5,
   "avg_path_pct": 4.6,
   "avg_range_pct": 3.5,
   "avg_largest_swing_pct": 3.2,
   "tradeable_pct": 4.8,
   "unusual_pct": 9.5,
   "character": "QUIET"
  },
  {
   "ticker": "SYM",
   "n_days": 21,
   "avg_eff": 0.503,
   "pct_trend": 61.9,
   "pct_chop": 28.6,
   "pct_mixed": 9.5,
   "avg_path_pct": 4.5,
   "avg_range_pct": 3.1,
   "avg_largest_swing_pct": 2.9,
   "tradeable_pct": 0.0,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "TER",
   "n_days": 21,
   "avg_eff": 0.511,
   "pct_trend": 47.6,
   "pct_chop": 19.0,
   "pct_mixed": 33.3,
   "avg_path_pct": 4.4,
   "avg_range_pct": 3.3,
   "avg_largest_swing_pct": 3.1,
   "tradeable_pct": 0.0,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "CRWD",
   "n_days": 21,
   "avg_eff": 0.525,
   "pct_trend": 66.7,
   "pct_chop": 23.8,
   "pct_mixed": 9.5,
   "avg_path_pct": 4.3,
   "avg_range_pct": 3.4,
   "avg_largest_swing_pct": 3.2,
   "tradeable_pct": 0.0,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "MU",
   "n_days": 21,
   "avg_eff": 0.473,
   "pct_trend": 47.6,
   "pct_chop": 38.1,
   "pct_mixed": 14.3,
   "avg_path_pct": 4.1,
   "avg_range_pct": 2.8,
   "avg_largest_swing_pct": 2.7,
   "tradeable_pct": 0.0,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "PLTR",
   "n_days": 21,
   "avg_eff": 0.616,
   "pct_trend": 66.7,
   "pct_chop": 14.3,
   "pct_mixed": 19.0,
   "avg_path_pct": 4.0,
   "avg_range_pct": 3.2,
   "avg_largest_swing_pct": 3.0,
   "tradeable_pct": 0.0,
   "unusual_pct": 14.3,
   "character": "QUIET"
  },
  {
   "ticker": "PANW",
   "n_days": 21,
   "avg_eff": 0.524,
   "pct_trend": 61.9,
   "pct_chop": 33.3,
   "pct_mixed": 4.8,
   "avg_path_pct": 4.0,
   "avg_range_pct": 3.2,
   "avg_largest_swing_pct": 3.1,
   "tradeable_pct": 0.0,
   "unusual_pct": 23.8,
   "character": "QUIET"
  },
  {
   "ticker": "TSM",
   "n_days": 21,
   "avg_eff": 0.529,
   "pct_trend": 57.1,
   "pct_chop": 23.8,
   "pct_mixed": 19.0,
   "avg_path_pct": 4.0,
   "avg_range_pct": 2.7,
   "avg_largest_swing_pct": 2.5,
   "tradeable_pct": 4.8,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "INTC",
   "n_days": 21,
   "avg_eff": 0.589,
   "pct_trend": 61.9,
   "pct_chop": 9.5,
   "pct_mixed": 28.6,
   "avg_path_pct": 4.0,
   "avg_range_pct": 3.0,
   "avg_largest_swing_pct": 2.8,
   "tradeable_pct": 4.8,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "KDEF",
   "n_days": 21,
   "avg_eff": 0.554,
   "pct_trend": 66.7,
   "pct_chop": 23.8,
   "pct_mixed": 9.5,
   "avg_path_pct": 4.0,
   "avg_range_pct": 3.0,
   "avg_largest_swing_pct": 2.8,
   "tradeable_pct": 4.8,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "GFS",
   "n_days": 21,
   "avg_eff": 0.607,
   "pct_trend": 71.4,
   "pct_chop": 14.3,
   "pct_mixed": 14.3,
   "avg_path_pct": 3.9,
   "avg_range_pct": 3.1,
   "avg_largest_swing_pct": 3.0,
   "tradeable_pct": 0.0,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "NU",
   "n_days": 21,
   "avg_eff": 0.502,
   "pct_trend": 57.1,
   "pct_chop": 28.6,
   "pct_mixed": 14.3,
   "avg_path_pct": 3.9,
   "avg_range_pct": 3.0,
   "avg_largest_swing_pct": 3.0,
   "tradeable_pct": 0.0,
   "unusual_pct": 14.3,
   "character": "QUIET"
  },
  {
   "ticker": "PKE",
   "n_days": 21,
   "avg_eff": 0.528,
   "pct_trend": 61.9,
   "pct_chop": 23.8,
   "pct_mixed": 14.3,
   "avg_path_pct": 3.9,
   "avg_range_pct": 3.0,
   "avg_largest_swing_pct": 2.8,
   "tradeable_pct": 0.0,
   "unusual_pct": 9.5,
   "character": "QUIET"
  },
  {
   "ticker": "ORCL",
   "n_days": 21,
   "avg_eff": 0.542,
   "pct_trend": 57.1,
   "pct_chop": 28.6,
   "pct_mixed": 14.3,
   "avg_path_pct": 3.8,
   "avg_range_pct": 2.9,
   "avg_largest_swing_pct": 2.8,
   "tradeable_pct": 0.0,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "U",
   "n_days": 21,
   "avg_eff": 0.549,
   "pct_trend": 57.1,
   "pct_chop": 19.0,
   "pct_mixed": 23.8,
   "avg_path_pct": 3.8,
   "avg_range_pct": 3.2,
   "avg_largest_swing_pct": 2.8,
   "tradeable_pct": 0.0,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "VRT",
   "n_days": 21,
   "avg_eff": 0.611,
   "pct_trend": 66.7,
   "pct_chop": 23.8,
   "pct_mixed": 9.5,
   "avg_path_pct": 3.8,
   "avg_range_pct": 3.1,
   "avg_largest_swing_pct": 2.8,
   "tradeable_pct": 4.8,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "NICE",
   "n_days": 21,
   "avg_eff": 0.677,
   "pct_trend": 76.2,
   "pct_chop": 14.3,
   "pct_mixed": 9.5,
   "avg_path_pct": 3.7,
   "avg_range_pct": 3.1,
   "avg_largest_swing_pct": 2.9,
   "tradeable_pct": 0.0,
   "unusual_pct": 28.6,
   "character": "QUIET"
  },
  {
   "ticker": "PINS",
   "n_days": 21,
   "avg_eff": 0.647,
   "pct_trend": 76.2,
   "pct_chop": 14.3,
   "pct_mixed": 9.5,
   "avg_path_pct": 3.7,
   "avg_range_pct": 3.3,
   "avg_largest_swing_pct": 3.0,
   "tradeable_pct": 4.8,
   "unusual_pct": 23.8,
   "character": "QUIET"
  },
  {
   "ticker": "ASML",
   "n_days": 21,
   "avg_eff": 0.542,
   "pct_trend": 57.1,
   "pct_chop": 23.8,
   "pct_mixed": 19.0,
   "avg_path_pct": 3.7,
   "avg_range_pct": 2.7,
   "avg_largest_swing_pct": 2.5,
   "tradeable_pct": 9.5,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "GLW",
   "n_days": 21,
   "avg_eff": 0.697,
   "pct_trend": 85.7,
   "pct_chop": 9.5,
   "pct_mixed": 4.8,
   "avg_path_pct": 3.7,
   "avg_range_pct": 3.3,
   "avg_largest_swing_pct": 3.0,
   "tradeable_pct": 0.0,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "SOFI",
   "n_days": 21,
   "avg_eff": 0.621,
   "pct_trend": 66.7,
   "pct_chop": 9.5,
   "pct_mixed": 23.8,
   "avg_path_pct": 3.7,
   "avg_range_pct": 3.0,
   "avg_largest_swing_pct": 2.8,
   "tradeable_pct": 0.0,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "CCJ",
   "n_days": 21,
   "avg_eff": 0.502,
   "pct_trend": 52.4,
   "pct_chop": 23.8,
   "pct_mixed": 23.8,
   "avg_path_pct": 3.7,
   "avg_range_pct": 2.8,
   "avg_largest_swing_pct": 2.6,
   "tradeable_pct": 4.8,
   "unusual_pct": 9.5,
   "character": "QUIET"
  },
  {
   "ticker": "JBLU",
   "n_days": 21,
   "avg_eff": 0.566,
   "pct_trend": 61.9,
   "pct_chop": 23.8,
   "pct_mixed": 14.3,
   "avg_path_pct": 3.7,
   "avg_range_pct": 2.9,
   "avg_largest_swing_pct": 2.7,
   "tradeable_pct": 0.0,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "NVDA",
   "n_days": 21,
   "avg_eff": 0.616,
   "pct_trend": 66.7,
   "pct_chop": 9.5,
   "pct_mixed": 23.8,
   "avg_path_pct": 3.6,
   "avg_range_pct": 2.8,
   "avg_largest_swing_pct": 2.7,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "NXPI",
   "n_days": 21,
   "avg_eff": 0.719,
   "pct_trend": 76.2,
   "pct_chop": 14.3,
   "pct_mixed": 9.5,
   "avg_path_pct": 3.6,
   "avg_range_pct": 3.0,
   "avg_largest_swing_pct": 2.8,
   "tradeable_pct": 4.8,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "MPWR",
   "n_days": 21,
   "avg_eff": 0.487,
   "pct_trend": 47.6,
   "pct_chop": 38.1,
   "pct_mixed": 14.3,
   "avg_path_pct": 3.6,
   "avg_range_pct": 2.9,
   "avg_largest_swing_pct": 2.7,
   "tradeable_pct": 0.0,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "LRCX",
   "n_days": 21,
   "avg_eff": 0.547,
   "pct_trend": 57.1,
   "pct_chop": 33.3,
   "pct_mixed": 9.5,
   "avg_path_pct": 3.6,
   "avg_range_pct": 3.0,
   "avg_largest_swing_pct": 2.7,
   "tradeable_pct": 0.0,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "BA",
   "n_days": 20,
   "avg_eff": 0.643,
   "pct_trend": 65.0,
   "pct_chop": 15.0,
   "pct_mixed": 20.0,
   "avg_path_pct": 3.6,
   "avg_range_pct": 2.8,
   "avg_largest_swing_pct": 2.7,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "CGNX",
   "n_days": 21,
   "avg_eff": 0.74,
   "pct_trend": 90.5,
   "pct_chop": 4.8,
   "pct_mixed": 4.8,
   "avg_path_pct": 3.6,
   "avg_range_pct": 3.2,
   "avg_largest_swing_pct": 3.0,
   "tradeable_pct": 0.0,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "CEG",
   "n_days": 21,
   "avg_eff": 0.649,
   "pct_trend": 76.2,
   "pct_chop": 19.0,
   "pct_mixed": 4.8,
   "avg_path_pct": 3.6,
   "avg_range_pct": 2.8,
   "avg_largest_swing_pct": 2.7,
   "tradeable_pct": 0.0,
   "unusual_pct": 42.9,
   "character": "QUIET"
  },
  {
   "ticker": "MBLY",
   "n_days": 21,
   "avg_eff": 0.546,
   "pct_trend": 57.1,
   "pct_chop": 23.8,
   "pct_mixed": 19.0,
   "avg_path_pct": 3.6,
   "avg_range_pct": 2.9,
   "avg_largest_swing_pct": 2.8,
   "tradeable_pct": 0.0,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "SNPS",
   "n_days": 21,
   "avg_eff": 0.744,
   "pct_trend": 81.0,
   "pct_chop": 0.0,
   "pct_mixed": 19.0,
   "avg_path_pct": 3.5,
   "avg_range_pct": 2.9,
   "avg_largest_swing_pct": 2.7,
   "tradeable_pct": 4.8,
   "unusual_pct": 19.0,
   "character": "QUIET"
  },
  {
   "ticker": "EBAY",
   "n_days": 21,
   "avg_eff": 0.716,
   "pct_trend": 76.2,
   "pct_chop": 9.5,
   "pct_mixed": 14.3,
   "avg_path_pct": 3.5,
   "avg_range_pct": 2.8,
   "avg_largest_swing_pct": 2.7,
   "tradeable_pct": 0.0,
   "unusual_pct": 33.3,
   "character": "QUIET"
  },
  {
   "ticker": "MCHP",
   "n_days": 21,
   "avg_eff": 0.666,
   "pct_trend": 76.2,
   "pct_chop": 9.5,
   "pct_mixed": 14.3,
   "avg_path_pct": 3.5,
   "avg_range_pct": 3.1,
   "avg_largest_swing_pct": 2.8,
   "tradeable_pct": 0.0,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "TSLA",
   "n_days": 21,
   "avg_eff": 0.594,
   "pct_trend": 61.9,
   "pct_chop": 19.0,
   "pct_mixed": 19.0,
   "avg_path_pct": 3.4,
   "avg_range_pct": 2.7,
   "avg_largest_swing_pct": 2.6,
   "tradeable_pct": 0.0,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "SHOP",
   "n_days": 21,
   "avg_eff": 0.706,
   "pct_trend": 81.0,
   "pct_chop": 9.5,
   "pct_mixed": 9.5,
   "avg_path_pct": 3.4,
   "avg_range_pct": 2.9,
   "avg_largest_swing_pct": 2.7,
   "tradeable_pct": 0.0,
   "unusual_pct": 14.3,
   "character": "QUIET"
  },
  {
   "ticker": "ANET",
   "n_days": 21,
   "avg_eff": 0.566,
   "pct_trend": 71.4,
   "pct_chop": 14.3,
   "pct_mixed": 14.3,
   "avg_path_pct": 3.4,
   "avg_range_pct": 2.7,
   "avg_largest_swing_pct": 2.5,
   "tradeable_pct": 0.0,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "DASH",
   "n_days": 21,
   "avg_eff": 0.632,
   "pct_trend": 71.4,
   "pct_chop": 23.8,
   "pct_mixed": 4.8,
   "avg_path_pct": 3.4,
   "avg_range_pct": 2.7,
   "avg_largest_swing_pct": 2.5,
   "tradeable_pct": 4.8,
   "unusual_pct": 19.0,
   "character": "QUIET"
  },
  {
   "ticker": "AMAT",
   "n_days": 21,
   "avg_eff": 0.583,
   "pct_trend": 71.4,
   "pct_chop": 23.8,
   "pct_mixed": 4.8,
   "avg_path_pct": 3.4,
   "avg_range_pct": 2.8,
   "avg_largest_swing_pct": 2.6,
   "tradeable_pct": 0.0,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "AAL",
   "n_days": 21,
   "avg_eff": 0.622,
   "pct_trend": 66.7,
   "pct_chop": 23.8,
   "pct_mixed": 9.5,
   "avg_path_pct": 3.4,
   "avg_range_pct": 2.8,
   "avg_largest_swing_pct": 2.6,
   "tradeable_pct": 0.0,
   "unusual_pct": 28.6,
   "character": "QUIET"
  },
  {
   "ticker": "Q",
   "n_days": 21,
   "avg_eff": 0.645,
   "pct_trend": 81.0,
   "pct_chop": 14.3,
   "pct_mixed": 4.8,
   "avg_path_pct": 3.4,
   "avg_range_pct": 3.0,
   "avg_largest_swing_pct": 2.7,
   "tradeable_pct": 0.0,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "QCOM",
   "n_days": 21,
   "avg_eff": 0.588,
   "pct_trend": 66.7,
   "pct_chop": 14.3,
   "pct_mixed": 19.0,
   "avg_path_pct": 3.3,
   "avg_range_pct": 2.9,
   "avg_largest_swing_pct": 2.7,
   "tradeable_pct": 0.0,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "HII",
   "n_days": 21,
   "avg_eff": 0.619,
   "pct_trend": 71.4,
   "pct_chop": 14.3,
   "pct_mixed": 14.3,
   "avg_path_pct": 3.3,
   "avg_range_pct": 3.0,
   "avg_largest_swing_pct": 2.7,
   "tradeable_pct": 4.8,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "MOG-A",
   "n_days": 21,
   "avg_eff": 0.575,
   "pct_trend": 66.7,
   "pct_chop": 28.6,
   "pct_mixed": 4.8,
   "avg_path_pct": 3.3,
   "avg_range_pct": 2.8,
   "avg_largest_swing_pct": 2.7,
   "tradeable_pct": 0.0,
   "unusual_pct": 19.0,
   "character": "QUIET"
  },
  {
   "ticker": "VZ",
   "n_days": 21,
   "avg_eff": 0.627,
   "pct_trend": 66.7,
   "pct_chop": 23.8,
   "pct_mixed": 9.5,
   "avg_path_pct": 3.3,
   "avg_range_pct": 2.5,
   "avg_largest_swing_pct": 2.5,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "KLAC",
   "n_days": 21,
   "avg_eff": 0.636,
   "pct_trend": 66.7,
   "pct_chop": 4.8,
   "pct_mixed": 28.6,
   "avg_path_pct": 3.2,
   "avg_range_pct": 2.8,
   "avg_largest_swing_pct": 2.6,
   "tradeable_pct": 0.0,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "XYZ",
   "n_days": 21,
   "avg_eff": 0.642,
   "pct_trend": 81.0,
   "pct_chop": 0.0,
   "pct_mixed": 19.0,
   "avg_path_pct": 3.2,
   "avg_range_pct": 2.7,
   "avg_largest_swing_pct": 2.6,
   "tradeable_pct": 0.0,
   "unusual_pct": 33.3,
   "character": "QUIET"
  },
  {
   "ticker": "CAT",
   "n_days": 21,
   "avg_eff": 0.614,
   "pct_trend": 76.2,
   "pct_chop": 19.0,
   "pct_mixed": 4.8,
   "avg_path_pct": 3.2,
   "avg_range_pct": 2.6,
   "avg_largest_swing_pct": 2.5,
   "tradeable_pct": 0.0,
   "unusual_pct": 19.0,
   "character": "QUIET"
  },
  {
   "ticker": "META",
   "n_days": 21,
   "avg_eff": 0.551,
   "pct_trend": 61.9,
   "pct_chop": 19.0,
   "pct_mixed": 19.0,
   "avg_path_pct": 3.1,
   "avg_range_pct": 2.5,
   "avg_largest_swing_pct": 2.5,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "IBM",
   "n_days": 21,
   "avg_eff": 0.628,
   "pct_trend": 81.0,
   "pct_chop": 14.3,
   "pct_mixed": 4.8,
   "avg_path_pct": 3.1,
   "avg_range_pct": 2.7,
   "avg_largest_swing_pct": 2.5,
   "tradeable_pct": 0.0,
   "unusual_pct": 19.0,
   "character": "QUIET"
  },
  {
   "ticker": "TXN",
   "n_days": 21,
   "avg_eff": 0.512,
   "pct_trend": 52.4,
   "pct_chop": 19.0,
   "pct_mixed": 28.6,
   "avg_path_pct": 3.1,
   "avg_range_pct": 2.3,
   "avg_largest_swing_pct": 2.2,
   "tradeable_pct": 4.8,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "CSCO",
   "n_days": 20,
   "avg_eff": 0.61,
   "pct_trend": 70.0,
   "pct_chop": 15.0,
   "pct_mixed": 15.0,
   "avg_path_pct": 3.0,
   "avg_range_pct": 2.4,
   "avg_largest_swing_pct": 2.3,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "AVGO",
   "n_days": 21,
   "avg_eff": 0.602,
   "pct_trend": 76.2,
   "pct_chop": 9.5,
   "pct_mixed": 14.3,
   "avg_path_pct": 3.0,
   "avg_range_pct": 2.6,
   "avg_largest_swing_pct": 2.5,
   "tradeable_pct": 4.8,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "ADI",
   "n_days": 21,
   "avg_eff": 0.65,
   "pct_trend": 71.4,
   "pct_chop": 19.0,
   "pct_mixed": 9.5,
   "avg_path_pct": 3.0,
   "avg_range_pct": 2.4,
   "avg_largest_swing_pct": 2.3,
   "tradeable_pct": 4.8,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "HWM",
   "n_days": 21,
   "avg_eff": 0.727,
   "pct_trend": 85.7,
   "pct_chop": 14.3,
   "pct_mixed": 0.0,
   "avg_path_pct": 3.0,
   "avg_range_pct": 2.6,
   "avg_largest_swing_pct": 2.4,
   "tradeable_pct": 0.0,
   "unusual_pct": 14.3,
   "character": "QUIET"
  },
  {
   "ticker": "NQ=F",
   "n_days": 11,
   "avg_eff": 0.799,
   "pct_trend": 90.9,
   "pct_chop": 0.0,
   "pct_mixed": 9.1,
   "avg_path_pct": 3.0,
   "avg_range_pct": 2.7,
   "avg_largest_swing_pct": 2.5,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "MOH",
   "n_days": 21,
   "avg_eff": 0.633,
   "pct_trend": 76.2,
   "pct_chop": 23.8,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.9,
   "avg_range_pct": 2.4,
   "avg_largest_swing_pct": 2.3,
   "tradeable_pct": 0.0,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "HUM",
   "n_days": 21,
   "avg_eff": 0.645,
   "pct_trend": 71.4,
   "pct_chop": 14.3,
   "pct_mixed": 14.3,
   "avg_path_pct": 2.9,
   "avg_range_pct": 2.6,
   "avg_largest_swing_pct": 2.4,
   "tradeable_pct": 0.0,
   "unusual_pct": 9.5,
   "character": "QUIET"
  },
  {
   "ticker": "TXT",
   "n_days": 18,
   "avg_eff": 0.618,
   "pct_trend": 77.8,
   "pct_chop": 16.7,
   "pct_mixed": 5.6,
   "avg_path_pct": 2.9,
   "avg_range_pct": 2.3,
   "avg_largest_swing_pct": 2.1,
   "tradeable_pct": 5.6,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "NMM",
   "n_days": 21,
   "avg_eff": 0.67,
   "pct_trend": 71.4,
   "pct_chop": 4.8,
   "pct_mixed": 23.8,
   "avg_path_pct": 2.9,
   "avg_range_pct": 2.7,
   "avg_largest_swing_pct": 2.5,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "MS",
   "n_days": 20,
   "avg_eff": 0.628,
   "pct_trend": 75.0,
   "pct_chop": 10.0,
   "pct_mixed": 15.0,
   "avg_path_pct": 2.9,
   "avg_range_pct": 2.4,
   "avg_largest_swing_pct": 2.3,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "GOOG",
   "n_days": 21,
   "avg_eff": 0.715,
   "pct_trend": 81.0,
   "pct_chop": 19.0,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.8,
   "avg_range_pct": 2.6,
   "avg_largest_swing_pct": 2.5,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "AMD",
   "n_days": 21,
   "avg_eff": 0.634,
   "pct_trend": 76.2,
   "pct_chop": 14.3,
   "pct_mixed": 9.5,
   "avg_path_pct": 2.8,
   "avg_range_pct": 2.6,
   "avg_largest_swing_pct": 2.3,
   "tradeable_pct": 0.0,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "HEI",
   "n_days": 20,
   "avg_eff": 0.622,
   "pct_trend": 80.0,
   "pct_chop": 10.0,
   "pct_mixed": 10.0,
   "avg_path_pct": 2.8,
   "avg_range_pct": 2.3,
   "avg_largest_swing_pct": 2.3,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "GE",
   "n_days": 18,
   "avg_eff": 0.685,
   "pct_trend": 72.2,
   "pct_chop": 5.6,
   "pct_mixed": 22.2,
   "avg_path_pct": 2.8,
   "avg_range_pct": 2.4,
   "avg_largest_swing_pct": 2.3,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "T",
   "n_days": 19,
   "avg_eff": 0.705,
   "pct_trend": 73.7,
   "pct_chop": 10.5,
   "pct_mixed": 15.8,
   "avg_path_pct": 2.8,
   "avg_range_pct": 2.6,
   "avg_largest_swing_pct": 2.5,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "UNH",
   "n_days": 17,
   "avg_eff": 0.733,
   "pct_trend": 88.2,
   "pct_chop": 0.0,
   "pct_mixed": 11.8,
   "avg_path_pct": 2.8,
   "avg_range_pct": 2.6,
   "avg_largest_swing_pct": 2.5,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "MSFT",
   "n_days": 17,
   "avg_eff": 0.645,
   "pct_trend": 76.5,
   "pct_chop": 11.8,
   "pct_mixed": 11.8,
   "avg_path_pct": 2.7,
   "avg_range_pct": 2.6,
   "avg_largest_swing_pct": 2.4,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "AMZN",
   "n_days": 16,
   "avg_eff": 0.604,
   "pct_trend": 62.5,
   "pct_chop": 12.5,
   "pct_mixed": 25.0,
   "avg_path_pct": 2.7,
   "avg_range_pct": 2.2,
   "avg_largest_swing_pct": 2.1,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "GM",
   "n_days": 21,
   "avg_eff": 0.683,
   "pct_trend": 76.2,
   "pct_chop": 14.3,
   "pct_mixed": 9.5,
   "avg_path_pct": 2.7,
   "avg_range_pct": 2.5,
   "avg_largest_swing_pct": 2.3,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "GS",
   "n_days": 21,
   "avg_eff": 0.683,
   "pct_trend": 85.7,
   "pct_chop": 9.5,
   "pct_mixed": 4.8,
   "avg_path_pct": 2.7,
   "avg_range_pct": 2.4,
   "avg_largest_swing_pct": 2.3,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "HON",
   "n_days": 21,
   "avg_eff": 0.636,
   "pct_trend": 71.4,
   "pct_chop": 9.5,
   "pct_mixed": 19.0,
   "avg_path_pct": 2.7,
   "avg_range_pct": 2.4,
   "avg_largest_swing_pct": 2.3,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "LHX",
   "n_days": 17,
   "avg_eff": 0.668,
   "pct_trend": 76.5,
   "pct_chop": 11.8,
   "pct_mixed": 11.8,
   "avg_path_pct": 2.6,
   "avg_range_pct": 2.3,
   "avg_largest_swing_pct": 2.2,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "TDG",
   "n_days": 17,
   "avg_eff": 0.768,
   "pct_trend": 82.4,
   "pct_chop": 17.6,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.6,
   "avg_range_pct": 2.4,
   "avg_largest_swing_pct": 2.3,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "HD",
   "n_days": 10,
   "avg_eff": 0.742,
   "pct_trend": 80.0,
   "pct_chop": 20.0,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.6,
   "avg_range_pct": 2.3,
   "avg_largest_swing_pct": 2.2,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "ABNB",
   "n_days": 21,
   "avg_eff": 0.661,
   "pct_trend": 76.2,
   "pct_chop": 9.5,
   "pct_mixed": 14.3,
   "avg_path_pct": 2.5,
   "avg_range_pct": 2.4,
   "avg_largest_swing_pct": 2.4,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "BABA",
   "n_days": 19,
   "avg_eff": 0.705,
   "pct_trend": 94.7,
   "pct_chop": 5.3,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.5,
   "avg_range_pct": 2.5,
   "avg_largest_swing_pct": 2.4,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "LLY",
   "n_days": 21,
   "avg_eff": 0.649,
   "pct_trend": 61.9,
   "pct_chop": 14.3,
   "pct_mixed": 23.8,
   "avg_path_pct": 2.5,
   "avg_range_pct": 2.1,
   "avg_largest_swing_pct": 2.0,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "BAC",
   "n_days": 11,
   "avg_eff": 0.718,
   "pct_trend": 81.8,
   "pct_chop": 18.2,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.5,
   "avg_range_pct": 2.2,
   "avg_largest_swing_pct": 2.1,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "NFLX",
   "n_days": 21,
   "avg_eff": 0.778,
   "pct_trend": 90.5,
   "pct_chop": 0.0,
   "pct_mixed": 9.5,
   "avg_path_pct": 2.4,
   "avg_range_pct": 2.5,
   "avg_largest_swing_pct": 2.3,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "LMT",
   "n_days": 19,
   "avg_eff": 0.812,
   "pct_trend": 89.5,
   "pct_chop": 10.5,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.4,
   "avg_range_pct": 2.3,
   "avg_largest_swing_pct": 2.1,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "SCHW",
   "n_days": 13,
   "avg_eff": 0.782,
   "pct_trend": 92.3,
   "pct_chop": 7.7,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.4,
   "avg_range_pct": 2.4,
   "avg_largest_swing_pct": 2.2,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "RTX",
   "n_days": 14,
   "avg_eff": 0.696,
   "pct_trend": 78.6,
   "pct_chop": 14.3,
   "pct_mixed": 7.1,
   "avg_path_pct": 2.3,
   "avg_range_pct": 2.2,
   "avg_largest_swing_pct": 2.1,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "NKE",
   "n_days": 21,
   "avg_eff": 0.737,
   "pct_trend": 85.7,
   "pct_chop": 9.5,
   "pct_mixed": 4.8,
   "avg_path_pct": 2.3,
   "avg_range_pct": 2.3,
   "avg_largest_swing_pct": 2.2,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "MRK",
   "n_days": 21,
   "avg_eff": 0.724,
   "pct_trend": 85.7,
   "pct_chop": 9.5,
   "pct_mixed": 4.8,
   "avg_path_pct": 2.3,
   "avg_range_pct": 2.1,
   "avg_largest_swing_pct": 2.0,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "PEP",
   "n_days": 8,
   "avg_eff": 0.831,
   "pct_trend": 100.0,
   "pct_chop": 0.0,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.3,
   "avg_range_pct": 2.4,
   "avg_largest_swing_pct": 2.3,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "WFC",
   "n_days": 20,
   "avg_eff": 0.755,
   "pct_trend": 85.0,
   "pct_chop": 0.0,
   "pct_mixed": 15.0,
   "avg_path_pct": 2.3,
   "avg_range_pct": 2.2,
   "avg_largest_swing_pct": 2.2,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "JPM",
   "n_days": 9,
   "avg_eff": 0.651,
   "pct_trend": 77.8,
   "pct_chop": 11.1,
   "pct_mixed": 11.1,
   "avg_path_pct": 2.2,
   "avg_range_pct": 2.0,
   "avg_largest_swing_pct": 2.0,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "NOC",
   "n_days": 19,
   "avg_eff": 0.821,
   "pct_trend": 94.7,
   "pct_chop": 0.0,
   "pct_mixed": 5.3,
   "avg_path_pct": 2.2,
   "avg_range_pct": 2.4,
   "avg_largest_swing_pct": 2.1,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "MO",
   "n_days": 15,
   "avg_eff": 0.793,
   "pct_trend": 93.3,
   "pct_chop": 6.7,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.2,
   "avg_range_pct": 2.3,
   "avg_largest_swing_pct": 2.1,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "UNP",
   "n_days": 13,
   "avg_eff": 0.784,
   "pct_trend": 92.3,
   "pct_chop": 7.7,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.2,
   "avg_range_pct": 2.3,
   "avg_largest_swing_pct": 2.1,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "XOM",
   "n_days": 10,
   "avg_eff": 0.682,
   "pct_trend": 80.0,
   "pct_chop": 10.0,
   "pct_mixed": 10.0,
   "avg_path_pct": 2.2,
   "avg_range_pct": 2.2,
   "avg_largest_swing_pct": 2.0,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "AAPL",
   "n_days": 21,
   "avg_eff": 0.799,
   "pct_trend": 95.2,
   "pct_chop": 4.8,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.1,
   "avg_range_pct": 2.1,
   "avg_largest_swing_pct": 2.0,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "ABBV",
   "n_days": 13,
   "avg_eff": 0.77,
   "pct_trend": 84.6,
   "pct_chop": 7.7,
   "pct_mixed": 7.7,
   "avg_path_pct": 2.1,
   "avg_range_pct": 2.2,
   "avg_largest_swing_pct": 2.0,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "CVS",
   "n_days": 21,
   "avg_eff": 0.78,
   "pct_trend": 95.2,
   "pct_chop": 4.8,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.1,
   "avg_range_pct": 2.2,
   "avg_largest_swing_pct": 2.0,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "JNJ",
   "n_days": 9,
   "avg_eff": 0.869,
   "pct_trend": 100.0,
   "pct_chop": 0.0,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.1,
   "avg_range_pct": 2.2,
   "avg_largest_swing_pct": 2.1,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "CVX",
   "n_days": 12,
   "avg_eff": 0.74,
   "pct_trend": 91.7,
   "pct_chop": 8.3,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.0,
   "avg_range_pct": 2.0,
   "avg_largest_swing_pct": 1.9,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "WMT",
   "n_days": 14,
   "avg_eff": 0.853,
   "pct_trend": 100.0,
   "pct_chop": 0.0,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.0,
   "avg_range_pct": 2.1,
   "avg_largest_swing_pct": 2.0,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "V",
   "n_days": 11,
   "avg_eff": 0.697,
   "pct_trend": 72.7,
   "pct_chop": 0.0,
   "pct_mixed": 27.3,
   "avg_path_pct": 1.9,
   "avg_range_pct": 2.0,
   "avg_largest_swing_pct": 1.9,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "GD",
   "n_days": 12,
   "avg_eff": 0.7,
   "pct_trend": 91.7,
   "pct_chop": 0.0,
   "pct_mixed": 8.3,
   "avg_path_pct": 1.9,
   "avg_range_pct": 2.1,
   "avg_largest_swing_pct": 1.9,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  }
 ],
 "failed": [
  "AVA",
  "KO",
  "ES=F",
  "BRK-B",
  "COST",
  "LIN",
  "PG"
 ]
};
