window.DAYTYPE_DATA = {
 "built_note": "15m bars, ~1mo per name",
 "n": 110,
 "tradeable_path_pct": 12.0,
 "rows": [
  {
   "ticker": "LPTH",
   "n_days": 20,
   "avg_eff": 0.258,
   "pct_trend": 20.0,
   "pct_chop": 35.0,
   "pct_mixed": 45.0,
   "avg_path_pct": 15.9,
   "avg_range_pct": 7.6,
   "avg_largest_swing_pct": 6.6,
   "tradeable_pct": 70.0,
   "character": "CHOPPY"
  },
  {
   "ticker": "NBIS",
   "n_days": 20,
   "avg_eff": 0.208,
   "pct_trend": 15.0,
   "pct_chop": 50.0,
   "pct_mixed": 35.0,
   "avg_path_pct": 15.1,
   "avg_range_pct": 7.1,
   "avg_largest_swing_pct": 6.7,
   "tradeable_pct": 75.0,
   "character": "CHOPPY"
  },
  {
   "ticker": "BE",
   "n_days": 20,
   "avg_eff": 0.314,
   "pct_trend": 30.0,
   "pct_chop": 40.0,
   "pct_mixed": 30.0,
   "avg_path_pct": 14.9,
   "avg_range_pct": 7.3,
   "avg_largest_swing_pct": 6.8,
   "tradeable_pct": 60.0,
   "character": "BALANCED"
  },
  {
   "ticker": "CBRS",
   "n_days": 20,
   "avg_eff": 0.347,
   "pct_trend": 40.0,
   "pct_chop": 35.0,
   "pct_mixed": 25.0,
   "avg_path_pct": 14.6,
   "avg_range_pct": 7.4,
   "avg_largest_swing_pct": 6.6,
   "tradeable_pct": 60.0,
   "character": "BALANCED"
  },
  {
   "ticker": "INFQ",
   "n_days": 20,
   "avg_eff": 0.284,
   "pct_trend": 35.0,
   "pct_chop": 60.0,
   "pct_mixed": 5.0,
   "avg_path_pct": 13.6,
   "avg_range_pct": 6.3,
   "avg_largest_swing_pct": 6.0,
   "tradeable_pct": 60.0,
   "character": "CHOPPY"
  },
  {
   "ticker": "IREN",
   "n_days": 20,
   "avg_eff": 0.333,
   "pct_trend": 30.0,
   "pct_chop": 30.0,
   "pct_mixed": 40.0,
   "avg_path_pct": 13.5,
   "avg_range_pct": 6.5,
   "avg_largest_swing_pct": 5.9,
   "tradeable_pct": 55.0,
   "character": "BALANCED"
  },
  {
   "ticker": "RGTI",
   "n_days": 20,
   "avg_eff": 0.362,
   "pct_trend": 40.0,
   "pct_chop": 35.0,
   "pct_mixed": 25.0,
   "avg_path_pct": 13.0,
   "avg_range_pct": 6.6,
   "avg_largest_swing_pct": 5.8,
   "tradeable_pct": 60.0,
   "character": "BALANCED"
  },
  {
   "ticker": "MRVL",
   "n_days": 20,
   "avg_eff": 0.317,
   "pct_trend": 35.0,
   "pct_chop": 45.0,
   "pct_mixed": 20.0,
   "avg_path_pct": 12.9,
   "avg_range_pct": 7.0,
   "avg_largest_swing_pct": 6.8,
   "tradeable_pct": 55.0,
   "character": "BALANCED"
  },
  {
   "ticker": "SNDK",
   "n_days": 20,
   "avg_eff": 0.346,
   "pct_trend": 30.0,
   "pct_chop": 40.0,
   "pct_mixed": 30.0,
   "avg_path_pct": 12.9,
   "avg_range_pct": 6.8,
   "avg_largest_swing_pct": 6.0,
   "tradeable_pct": 55.0,
   "character": "BALANCED"
  },
  {
   "ticker": "IONQ",
   "n_days": 20,
   "avg_eff": 0.312,
   "pct_trend": 30.0,
   "pct_chop": 30.0,
   "pct_mixed": 40.0,
   "avg_path_pct": 12.8,
   "avg_range_pct": 6.5,
   "avg_largest_swing_pct": 6.1,
   "tradeable_pct": 60.0,
   "character": "BALANCED"
  },
  {
   "ticker": "QBTS",
   "n_days": 20,
   "avg_eff": 0.306,
   "pct_trend": 40.0,
   "pct_chop": 40.0,
   "pct_mixed": 20.0,
   "avg_path_pct": 12.8,
   "avg_range_pct": 6.2,
   "avg_largest_swing_pct": 5.7,
   "tradeable_pct": 55.0,
   "character": "BALANCED"
  },
  {
   "ticker": "SMR",
   "n_days": 19,
   "avg_eff": 0.302,
   "pct_trend": 36.8,
   "pct_chop": 47.4,
   "pct_mixed": 15.8,
   "avg_path_pct": 12.5,
   "avg_range_pct": 6.2,
   "avg_largest_swing_pct": 5.7,
   "tradeable_pct": 57.9,
   "character": "BALANCED"
  },
  {
   "ticker": "SPCX",
   "n_days": 16,
   "avg_eff": 0.397,
   "pct_trend": 37.5,
   "pct_chop": 25.0,
   "pct_mixed": 37.5,
   "avg_path_pct": 12.5,
   "avg_range_pct": 7.0,
   "avg_largest_swing_pct": 6.5,
   "tradeable_pct": 50.0,
   "character": "BALANCED"
  },
  {
   "ticker": "INOD",
   "n_days": 20,
   "avg_eff": 0.308,
   "pct_trend": 25.0,
   "pct_chop": 40.0,
   "pct_mixed": 35.0,
   "avg_path_pct": 11.6,
   "avg_range_pct": 6.0,
   "avg_largest_swing_pct": 5.7,
   "tradeable_pct": 25.0,
   "character": "BALANCED"
  },
  {
   "ticker": "ASTS",
   "n_days": 20,
   "avg_eff": 0.369,
   "pct_trend": 35.0,
   "pct_chop": 35.0,
   "pct_mixed": 30.0,
   "avg_path_pct": 11.6,
   "avg_range_pct": 6.5,
   "avg_largest_swing_pct": 5.9,
   "tradeable_pct": 45.0,
   "character": "BALANCED"
  },
  {
   "ticker": "MU",
   "n_days": 20,
   "avg_eff": 0.343,
   "pct_trend": 30.0,
   "pct_chop": 40.0,
   "pct_mixed": 30.0,
   "avg_path_pct": 11.5,
   "avg_range_pct": 6.1,
   "avg_largest_swing_pct": 5.8,
   "tradeable_pct": 55.0,
   "character": "BALANCED"
  },
  {
   "ticker": "ARM",
   "n_days": 19,
   "avg_eff": 0.38,
   "pct_trend": 36.8,
   "pct_chop": 36.8,
   "pct_mixed": 26.3,
   "avg_path_pct": 11.4,
   "avg_range_pct": 6.7,
   "avg_largest_swing_pct": 6.3,
   "tradeable_pct": 47.4,
   "character": "BALANCED"
  },
  {
   "ticker": "GLW",
   "n_days": 19,
   "avg_eff": 0.451,
   "pct_trend": 57.9,
   "pct_chop": 21.1,
   "pct_mixed": 21.1,
   "avg_path_pct": 11.4,
   "avg_range_pct": 6.9,
   "avg_largest_swing_pct": 6.7,
   "tradeable_pct": 31.6,
   "character": "TRENDY"
  },
  {
   "ticker": "RKLB",
   "n_days": 19,
   "avg_eff": 0.313,
   "pct_trend": 36.8,
   "pct_chop": 42.1,
   "pct_mixed": 21.1,
   "avg_path_pct": 11.4,
   "avg_range_pct": 6.0,
   "avg_largest_swing_pct": 5.7,
   "tradeable_pct": 36.8,
   "character": "BALANCED"
  },
  {
   "ticker": "LASR",
   "n_days": 20,
   "avg_eff": 0.353,
   "pct_trend": 40.0,
   "pct_chop": 40.0,
   "pct_mixed": 20.0,
   "avg_path_pct": 10.6,
   "avg_range_pct": 5.9,
   "avg_largest_swing_pct": 5.5,
   "tradeable_pct": 30.0,
   "character": "BALANCED"
  },
  {
   "ticker": "INTC",
   "n_days": 20,
   "avg_eff": 0.351,
   "pct_trend": 35.0,
   "pct_chop": 40.0,
   "pct_mixed": 25.0,
   "avg_path_pct": 10.5,
   "avg_range_pct": 5.8,
   "avg_largest_swing_pct": 5.5,
   "tradeable_pct": 40.0,
   "character": "BALANCED"
  },
  {
   "ticker": "CRWV",
   "n_days": 20,
   "avg_eff": 0.293,
   "pct_trend": 30.0,
   "pct_chop": 40.0,
   "pct_mixed": 30.0,
   "avg_path_pct": 10.4,
   "avg_range_pct": 5.0,
   "avg_largest_swing_pct": 4.7,
   "tradeable_pct": 45.0,
   "character": "CHOPPY"
  },
  {
   "ticker": "SMCI",
   "n_days": 20,
   "avg_eff": 0.459,
   "pct_trend": 45.0,
   "pct_chop": 15.0,
   "pct_mixed": 40.0,
   "avg_path_pct": 10.2,
   "avg_range_pct": 6.2,
   "avg_largest_swing_pct": 5.4,
   "tradeable_pct": 30.0,
   "character": "TRENDY"
  },
  {
   "ticker": "TSEM",
   "n_days": 20,
   "avg_eff": 0.363,
   "pct_trend": 40.0,
   "pct_chop": 35.0,
   "pct_mixed": 25.0,
   "avg_path_pct": 10.2,
   "avg_range_pct": 5.9,
   "avg_largest_swing_pct": 5.5,
   "tradeable_pct": 30.0,
   "character": "BALANCED"
  },
  {
   "ticker": "OKLO",
   "n_days": 19,
   "avg_eff": 0.273,
   "pct_trend": 15.8,
   "pct_chop": 36.8,
   "pct_mixed": 47.4,
   "avg_path_pct": 10.2,
   "avg_range_pct": 5.1,
   "avg_largest_swing_pct": 4.7,
   "tradeable_pct": 47.4,
   "character": "CHOPPY"
  },
  {
   "ticker": "ONDS",
   "n_days": 20,
   "avg_eff": 0.452,
   "pct_trend": 50.0,
   "pct_chop": 35.0,
   "pct_mixed": 15.0,
   "avg_path_pct": 10.1,
   "avg_range_pct": 5.7,
   "avg_largest_swing_pct": 5.3,
   "tradeable_pct": 35.0,
   "character": "TRENDY"
  },
  {
   "ticker": "TER",
   "n_days": 18,
   "avg_eff": 0.56,
   "pct_trend": 61.1,
   "pct_chop": 5.6,
   "pct_mixed": 33.3,
   "avg_path_pct": 9.9,
   "avg_range_pct": 6.4,
   "avg_largest_swing_pct": 6.0,
   "tradeable_pct": 33.3,
   "character": "TRENDY"
  },
  {
   "ticker": "WDC",
   "n_days": 20,
   "avg_eff": 0.34,
   "pct_trend": 30.0,
   "pct_chop": 40.0,
   "pct_mixed": 30.0,
   "avg_path_pct": 9.7,
   "avg_range_pct": 5.7,
   "avg_largest_swing_pct": 5.3,
   "tradeable_pct": 30.0,
   "character": "BALANCED"
  },
  {
   "ticker": "STX",
   "n_days": 20,
   "avg_eff": 0.378,
   "pct_trend": 30.0,
   "pct_chop": 35.0,
   "pct_mixed": 35.0,
   "avg_path_pct": 9.4,
   "avg_range_pct": 5.8,
   "avg_largest_swing_pct": 5.6,
   "tradeable_pct": 25.0,
   "character": "BALANCED"
  },
  {
   "ticker": "LRCX",
   "n_days": 19,
   "avg_eff": 0.426,
   "pct_trend": 42.1,
   "pct_chop": 15.8,
   "pct_mixed": 42.1,
   "avg_path_pct": 9.2,
   "avg_range_pct": 5.4,
   "avg_largest_swing_pct": 5.0,
   "tradeable_pct": 21.1,
   "character": "BALANCED"
  },
  {
   "ticker": "DELL",
   "n_days": 20,
   "avg_eff": 0.379,
   "pct_trend": 35.0,
   "pct_chop": 20.0,
   "pct_mixed": 45.0,
   "avg_path_pct": 8.9,
   "avg_range_pct": 5.4,
   "avg_largest_swing_pct": 5.0,
   "tradeable_pct": 20.0,
   "character": "BALANCED"
  },
  {
   "ticker": "PCT",
   "n_days": 19,
   "avg_eff": 0.501,
   "pct_trend": 63.2,
   "pct_chop": 15.8,
   "pct_mixed": 21.1,
   "avg_path_pct": 8.9,
   "avg_range_pct": 6.0,
   "avg_largest_swing_pct": 5.8,
   "tradeable_pct": 5.3,
   "character": "TRENDY"
  },
  {
   "ticker": "RDDT",
   "n_days": 19,
   "avg_eff": 0.369,
   "pct_trend": 26.3,
   "pct_chop": 36.8,
   "pct_mixed": 36.8,
   "avg_path_pct": 8.8,
   "avg_range_pct": 4.8,
   "avg_largest_swing_pct": 4.4,
   "tradeable_pct": 26.3,
   "character": "BALANCED"
  },
  {
   "ticker": "HOOD",
   "n_days": 20,
   "avg_eff": 0.384,
   "pct_trend": 40.0,
   "pct_chop": 25.0,
   "pct_mixed": 35.0,
   "avg_path_pct": 8.7,
   "avg_range_pct": 5.1,
   "avg_largest_swing_pct": 4.7,
   "tradeable_pct": 15.0,
   "character": "BALANCED"
  },
  {
   "ticker": "KLAC",
   "n_days": 19,
   "avg_eff": 0.477,
   "pct_trend": 57.9,
   "pct_chop": 15.8,
   "pct_mixed": 26.3,
   "avg_path_pct": 8.4,
   "avg_range_pct": 5.8,
   "avg_largest_swing_pct": 5.5,
   "tradeable_pct": 26.3,
   "character": "TRENDY"
  },
  {
   "ticker": "AMD",
   "n_days": 18,
   "avg_eff": 0.348,
   "pct_trend": 22.2,
   "pct_chop": 50.0,
   "pct_mixed": 27.8,
   "avg_path_pct": 8.2,
   "avg_range_pct": 4.7,
   "avg_largest_swing_pct": 4.6,
   "tradeable_pct": 11.1,
   "character": "BALANCED"
  },
  {
   "ticker": "QCOM",
   "n_days": 19,
   "avg_eff": 0.454,
   "pct_trend": 42.1,
   "pct_chop": 36.8,
   "pct_mixed": 21.1,
   "avg_path_pct": 8.0,
   "avg_range_pct": 4.8,
   "avg_largest_swing_pct": 4.5,
   "tradeable_pct": 15.8,
   "character": "TRENDY"
  },
  {
   "ticker": "ON",
   "n_days": 20,
   "avg_eff": 0.403,
   "pct_trend": 50.0,
   "pct_chop": 20.0,
   "pct_mixed": 30.0,
   "avg_path_pct": 8.0,
   "avg_range_pct": 4.5,
   "avg_largest_swing_pct": 4.3,
   "tradeable_pct": 10.0,
   "character": "BALANCED"
  },
  {
   "ticker": "GFS",
   "n_days": 17,
   "avg_eff": 0.387,
   "pct_trend": 41.2,
   "pct_chop": 35.3,
   "pct_mixed": 23.5,
   "avg_path_pct": 8.0,
   "avg_range_pct": 4.8,
   "avg_largest_swing_pct": 4.4,
   "tradeable_pct": 5.9,
   "character": "BALANCED"
  },
  {
   "ticker": "AMAT",
   "n_days": 20,
   "avg_eff": 0.493,
   "pct_trend": 55.0,
   "pct_chop": 25.0,
   "pct_mixed": 20.0,
   "avg_path_pct": 7.7,
   "avg_range_pct": 5.2,
   "avg_largest_swing_pct": 4.9,
   "tradeable_pct": 10.0,
   "character": "QUIET"
  },
  {
   "ticker": "MBLY",
   "n_days": 16,
   "avg_eff": 0.488,
   "pct_trend": 68.8,
   "pct_chop": 25.0,
   "pct_mixed": 6.2,
   "avg_path_pct": 7.7,
   "avg_range_pct": 5.1,
   "avg_largest_swing_pct": 4.5,
   "tradeable_pct": 18.8,
   "character": "QUIET"
  },
  {
   "ticker": "MPWR",
   "n_days": 19,
   "avg_eff": 0.364,
   "pct_trend": 31.6,
   "pct_chop": 36.8,
   "pct_mixed": 31.6,
   "avg_path_pct": 7.6,
   "avg_range_pct": 4.7,
   "avg_largest_swing_pct": 4.5,
   "tradeable_pct": 5.3,
   "character": "QUIET"
  },
  {
   "ticker": "COIN",
   "n_days": 20,
   "avg_eff": 0.437,
   "pct_trend": 50.0,
   "pct_chop": 15.0,
   "pct_mixed": 35.0,
   "avg_path_pct": 7.6,
   "avg_range_pct": 4.9,
   "avg_largest_swing_pct": 4.7,
   "tradeable_pct": 5.0,
   "character": "QUIET"
  },
  {
   "ticker": "CTMX",
   "n_days": 19,
   "avg_eff": 0.379,
   "pct_trend": 42.1,
   "pct_chop": 31.6,
   "pct_mixed": 26.3,
   "avg_path_pct": 7.5,
   "avg_range_pct": 4.1,
   "avg_largest_swing_pct": 4.1,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "SOUN",
   "n_days": 20,
   "avg_eff": 0.439,
   "pct_trend": 50.0,
   "pct_chop": 25.0,
   "pct_mixed": 25.0,
   "avg_path_pct": 7.5,
   "avg_range_pct": 4.9,
   "avg_largest_swing_pct": 4.6,
   "tradeable_pct": 10.0,
   "character": "QUIET"
  },
  {
   "ticker": "KTOS",
   "n_days": 20,
   "avg_eff": 0.414,
   "pct_trend": 45.0,
   "pct_chop": 25.0,
   "pct_mixed": 30.0,
   "avg_path_pct": 7.4,
   "avg_range_pct": 4.3,
   "avg_largest_swing_pct": 4.1,
   "tradeable_pct": 5.0,
   "character": "QUIET"
  },
  {
   "ticker": "AVAV",
   "n_days": 20,
   "avg_eff": 0.515,
   "pct_trend": 50.0,
   "pct_chop": 20.0,
   "pct_mixed": 30.0,
   "avg_path_pct": 7.2,
   "avg_range_pct": 4.2,
   "avg_largest_swing_pct": 3.7,
   "tradeable_pct": 15.0,
   "character": "QUIET"
  },
  {
   "ticker": "SYM",
   "n_days": 17,
   "avg_eff": 0.503,
   "pct_trend": 58.8,
   "pct_chop": 17.6,
   "pct_mixed": 23.5,
   "avg_path_pct": 7.2,
   "avg_range_pct": 4.6,
   "avg_largest_swing_pct": 4.2,
   "tradeable_pct": 17.6,
   "character": "QUIET"
  },
  {
   "ticker": "Q",
   "n_days": 18,
   "avg_eff": 0.544,
   "pct_trend": 55.6,
   "pct_chop": 22.2,
   "pct_mixed": 22.2,
   "avg_path_pct": 7.1,
   "avg_range_pct": 4.9,
   "avg_largest_swing_pct": 4.6,
   "tradeable_pct": 16.7,
   "character": "QUIET"
  },
  {
   "ticker": "VRT",
   "n_days": 18,
   "avg_eff": 0.448,
   "pct_trend": 44.4,
   "pct_chop": 27.8,
   "pct_mixed": 27.8,
   "avg_path_pct": 7.0,
   "avg_range_pct": 4.5,
   "avg_largest_swing_pct": 4.3,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "IOT",
   "n_days": 18,
   "avg_eff": 0.473,
   "pct_trend": 33.3,
   "pct_chop": 11.1,
   "pct_mixed": 55.6,
   "avg_path_pct": 6.8,
   "avg_range_pct": 4.4,
   "avg_largest_swing_pct": 4.1,
   "tradeable_pct": 5.6,
   "character": "QUIET"
  },
  {
   "ticker": "HPE",
   "n_days": 18,
   "avg_eff": 0.32,
   "pct_trend": 27.8,
   "pct_chop": 50.0,
   "pct_mixed": 22.2,
   "avg_path_pct": 6.6,
   "avg_range_pct": 4.2,
   "avg_largest_swing_pct": 4.0,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "SOFI",
   "n_days": 16,
   "avg_eff": 0.537,
   "pct_trend": 56.2,
   "pct_chop": 12.5,
   "pct_mixed": 31.2,
   "avg_path_pct": 6.5,
   "avg_range_pct": 4.6,
   "avg_largest_swing_pct": 4.4,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "CVNA",
   "n_days": 20,
   "avg_eff": 0.46,
   "pct_trend": 60.0,
   "pct_chop": 20.0,
   "pct_mixed": 20.0,
   "avg_path_pct": 6.5,
   "avg_range_pct": 4.4,
   "avg_largest_swing_pct": 4.1,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "U",
   "n_days": 16,
   "avg_eff": 0.534,
   "pct_trend": 62.5,
   "pct_chop": 18.8,
   "pct_mixed": 18.8,
   "avg_path_pct": 6.4,
   "avg_range_pct": 4.4,
   "avg_largest_swing_pct": 4.1,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "AXON",
   "n_days": 20,
   "avg_eff": 0.417,
   "pct_trend": 40.0,
   "pct_chop": 35.0,
   "pct_mixed": 25.0,
   "avg_path_pct": 6.3,
   "avg_range_pct": 4.1,
   "avg_largest_swing_pct": 3.8,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "ANET",
   "n_days": 19,
   "avg_eff": 0.41,
   "pct_trend": 42.1,
   "pct_chop": 36.8,
   "pct_mixed": 21.1,
   "avg_path_pct": 6.0,
   "avg_range_pct": 3.9,
   "avg_largest_swing_pct": 3.7,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "RBLX",
   "n_days": 18,
   "avg_eff": 0.492,
   "pct_trend": 72.2,
   "pct_chop": 22.2,
   "pct_mixed": 5.6,
   "avg_path_pct": 5.9,
   "avg_range_pct": 4.0,
   "avg_largest_swing_pct": 3.9,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "PKE",
   "n_days": 20,
   "avg_eff": 0.552,
   "pct_trend": 60.0,
   "pct_chop": 20.0,
   "pct_mixed": 20.0,
   "avg_path_pct": 5.6,
   "avg_range_pct": 4.1,
   "avg_largest_swing_pct": 3.6,
   "tradeable_pct": 5.0,
   "character": "QUIET"
  },
  {
   "ticker": "OKTA",
   "n_days": 19,
   "avg_eff": 0.465,
   "pct_trend": 47.4,
   "pct_chop": 26.3,
   "pct_mixed": 26.3,
   "avg_path_pct": 5.4,
   "avg_range_pct": 3.7,
   "avg_largest_swing_pct": 3.4,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "CCJ",
   "n_days": 15,
   "avg_eff": 0.521,
   "pct_trend": 53.3,
   "pct_chop": 26.7,
   "pct_mixed": 20.0,
   "avg_path_pct": 5.4,
   "avg_range_pct": 3.9,
   "avg_largest_swing_pct": 3.7,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "CRWD",
   "n_days": 13,
   "avg_eff": 0.422,
   "pct_trend": 38.5,
   "pct_chop": 53.8,
   "pct_mixed": 7.7,
   "avg_path_pct": 5.3,
   "avg_range_pct": 3.4,
   "avg_largest_swing_pct": 3.2,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "SHOP",
   "n_days": 15,
   "avg_eff": 0.559,
   "pct_trend": 60.0,
   "pct_chop": 13.3,
   "pct_mixed": 26.7,
   "avg_path_pct": 5.3,
   "avg_range_pct": 3.9,
   "avg_largest_swing_pct": 3.5,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "MCHP",
   "n_days": 19,
   "avg_eff": 0.493,
   "pct_trend": 52.6,
   "pct_chop": 36.8,
   "pct_mixed": 10.5,
   "avg_path_pct": 5.3,
   "avg_range_pct": 3.9,
   "avg_largest_swing_pct": 3.6,
   "tradeable_pct": 5.3,
   "character": "QUIET"
  },
  {
   "ticker": "CGNX",
   "n_days": 16,
   "avg_eff": 0.58,
   "pct_trend": 68.8,
   "pct_chop": 18.8,
   "pct_mixed": 12.5,
   "avg_path_pct": 5.3,
   "avg_range_pct": 4.0,
   "avg_largest_swing_pct": 3.8,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "ORCL",
   "n_days": 19,
   "avg_eff": 0.614,
   "pct_trend": 68.4,
   "pct_chop": 5.3,
   "pct_mixed": 26.3,
   "avg_path_pct": 5.2,
   "avg_range_pct": 3.9,
   "avg_largest_swing_pct": 3.7,
   "tradeable_pct": 5.3,
   "character": "QUIET"
  },
  {
   "ticker": "NXPI",
   "n_days": 17,
   "avg_eff": 0.447,
   "pct_trend": 47.1,
   "pct_chop": 23.5,
   "pct_mixed": 29.4,
   "avg_path_pct": 5.0,
   "avg_range_pct": 3.6,
   "avg_largest_swing_pct": 3.5,
   "tradeable_pct": 5.9,
   "character": "QUIET"
  },
  {
   "ticker": "ASML",
   "n_days": 17,
   "avg_eff": 0.505,
   "pct_trend": 58.8,
   "pct_chop": 23.5,
   "pct_mixed": 17.6,
   "avg_path_pct": 4.9,
   "avg_range_pct": 3.6,
   "avg_largest_swing_pct": 3.4,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "NU",
   "n_days": 15,
   "avg_eff": 0.519,
   "pct_trend": 53.3,
   "pct_chop": 33.3,
   "pct_mixed": 13.3,
   "avg_path_pct": 4.9,
   "avg_range_pct": 3.4,
   "avg_largest_swing_pct": 3.2,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "SNPS",
   "n_days": 14,
   "avg_eff": 0.368,
   "pct_trend": 35.7,
   "pct_chop": 42.9,
   "pct_mixed": 21.4,
   "avg_path_pct": 4.8,
   "avg_range_pct": 3.3,
   "avg_largest_swing_pct": 3.2,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "AVGO",
   "n_days": 14,
   "avg_eff": 0.427,
   "pct_trend": 35.7,
   "pct_chop": 42.9,
   "pct_mixed": 21.4,
   "avg_path_pct": 4.7,
   "avg_range_pct": 3.1,
   "avg_largest_swing_pct": 3.0,
   "tradeable_pct": 7.1,
   "character": "QUIET"
  },
  {
   "ticker": "MOH",
   "n_days": 13,
   "avg_eff": 0.556,
   "pct_trend": 69.2,
   "pct_chop": 15.4,
   "pct_mixed": 15.4,
   "avg_path_pct": 4.6,
   "avg_range_pct": 3.4,
   "avg_largest_swing_pct": 3.1,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "KDEF",
   "n_days": 14,
   "avg_eff": 0.455,
   "pct_trend": 42.9,
   "pct_chop": 28.6,
   "pct_mixed": 28.6,
   "avg_path_pct": 4.6,
   "avg_range_pct": 3.3,
   "avg_largest_swing_pct": 3.1,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "PLTR",
   "n_days": 18,
   "avg_eff": 0.514,
   "pct_trend": 50.0,
   "pct_chop": 27.8,
   "pct_mixed": 22.2,
   "avg_path_pct": 4.5,
   "avg_range_pct": 3.5,
   "avg_largest_swing_pct": 3.2,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "TSLA",
   "n_days": 17,
   "avg_eff": 0.715,
   "pct_trend": 82.4,
   "pct_chop": 5.9,
   "pct_mixed": 11.8,
   "avg_path_pct": 4.4,
   "avg_range_pct": 3.9,
   "avg_largest_swing_pct": 3.7,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "NICE",
   "n_days": 12,
   "avg_eff": 0.577,
   "pct_trend": 66.7,
   "pct_chop": 25.0,
   "pct_mixed": 8.3,
   "avg_path_pct": 4.4,
   "avg_range_pct": 3.5,
   "avg_largest_swing_pct": 3.0,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "TSM",
   "n_days": 15,
   "avg_eff": 0.673,
   "pct_trend": 66.7,
   "pct_chop": 6.7,
   "pct_mixed": 26.7,
   "avg_path_pct": 4.4,
   "avg_range_pct": 3.5,
   "avg_largest_swing_pct": 3.2,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "DASH",
   "n_days": 16,
   "avg_eff": 0.683,
   "pct_trend": 75.0,
   "pct_chop": 6.2,
   "pct_mixed": 18.8,
   "avg_path_pct": 4.3,
   "avg_range_pct": 3.6,
   "avg_largest_swing_pct": 3.2,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "PINS",
   "n_days": 17,
   "avg_eff": 0.526,
   "pct_trend": 58.8,
   "pct_chop": 23.5,
   "pct_mixed": 17.6,
   "avg_path_pct": 4.3,
   "avg_range_pct": 3.4,
   "avg_largest_swing_pct": 3.2,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "TXN",
   "n_days": 14,
   "avg_eff": 0.662,
   "pct_trend": 78.6,
   "pct_chop": 21.4,
   "pct_mixed": 0.0,
   "avg_path_pct": 4.2,
   "avg_range_pct": 3.6,
   "avg_largest_swing_pct": 3.3,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "ADI",
   "n_days": 17,
   "avg_eff": 0.623,
   "pct_trend": 70.6,
   "pct_chop": 29.4,
   "pct_mixed": 0.0,
   "avg_path_pct": 4.2,
   "avg_range_pct": 3.2,
   "avg_largest_swing_pct": 2.9,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "CAT",
   "n_days": 14,
   "avg_eff": 0.668,
   "pct_trend": 78.6,
   "pct_chop": 14.3,
   "pct_mixed": 7.1,
   "avg_path_pct": 4.0,
   "avg_range_pct": 3.4,
   "avg_largest_swing_pct": 3.0,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "AAL",
   "n_days": 16,
   "avg_eff": 0.688,
   "pct_trend": 81.2,
   "pct_chop": 12.5,
   "pct_mixed": 6.2,
   "avg_path_pct": 4.0,
   "avg_range_pct": 3.5,
   "avg_largest_swing_pct": 3.4,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "CEG",
   "n_days": 11,
   "avg_eff": 0.49,
   "pct_trend": 54.5,
   "pct_chop": 9.1,
   "pct_mixed": 36.4,
   "avg_path_pct": 4.0,
   "avg_range_pct": 3.0,
   "avg_largest_swing_pct": 2.9,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "XYZ",
   "n_days": 16,
   "avg_eff": 0.643,
   "pct_trend": 81.2,
   "pct_chop": 6.2,
   "pct_mixed": 12.5,
   "avg_path_pct": 3.7,
   "avg_range_pct": 3.2,
   "avg_largest_swing_pct": 3.0,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "NKE",
   "n_days": 12,
   "avg_eff": 0.612,
   "pct_trend": 75.0,
   "pct_chop": 16.7,
   "pct_mixed": 8.3,
   "avg_path_pct": 3.7,
   "avg_range_pct": 2.9,
   "avg_largest_swing_pct": 2.7,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "PANW",
   "n_days": 16,
   "avg_eff": 0.658,
   "pct_trend": 68.8,
   "pct_chop": 18.8,
   "pct_mixed": 12.5,
   "avg_path_pct": 3.6,
   "avg_range_pct": 3.1,
   "avg_largest_swing_pct": 3.0,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "CSCO",
   "n_days": 9,
   "avg_eff": 0.535,
   "pct_trend": 55.6,
   "pct_chop": 22.2,
   "pct_mixed": 22.2,
   "avg_path_pct": 3.6,
   "avg_range_pct": 2.9,
   "avg_largest_swing_pct": 2.8,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "MOG-A",
   "n_days": 16,
   "avg_eff": 0.504,
   "pct_trend": 50.0,
   "pct_chop": 31.2,
   "pct_mixed": 18.8,
   "avg_path_pct": 3.6,
   "avg_range_pct": 2.8,
   "avg_largest_swing_pct": 2.6,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "GM",
   "n_days": 9,
   "avg_eff": 0.602,
   "pct_trend": 66.7,
   "pct_chop": 33.3,
   "pct_mixed": 0.0,
   "avg_path_pct": 3.6,
   "avg_range_pct": 3.0,
   "avg_largest_swing_pct": 2.8,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "NFLX",
   "n_days": 9,
   "avg_eff": 0.751,
   "pct_trend": 88.9,
   "pct_chop": 11.1,
   "pct_mixed": 0.0,
   "avg_path_pct": 3.3,
   "avg_range_pct": 3.1,
   "avg_largest_swing_pct": 2.9,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "HUM",
   "n_days": 18,
   "avg_eff": 0.644,
   "pct_trend": 77.8,
   "pct_chop": 11.1,
   "pct_mixed": 11.1,
   "avg_path_pct": 3.3,
   "avg_range_pct": 2.8,
   "avg_largest_swing_pct": 2.6,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "HEI",
   "n_days": 9,
   "avg_eff": 0.612,
   "pct_trend": 77.8,
   "pct_chop": 22.2,
   "pct_mixed": 0.0,
   "avg_path_pct": 3.2,
   "avg_range_pct": 2.8,
   "avg_largest_swing_pct": 2.6,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "HWM",
   "n_days": 14,
   "avg_eff": 0.579,
   "pct_trend": 64.3,
   "pct_chop": 14.3,
   "pct_mixed": 21.4,
   "avg_path_pct": 3.2,
   "avg_range_pct": 2.9,
   "avg_largest_swing_pct": 2.6,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "META",
   "n_days": 12,
   "avg_eff": 0.639,
   "pct_trend": 75.0,
   "pct_chop": 16.7,
   "pct_mixed": 8.3,
   "avg_path_pct": 3.1,
   "avg_range_pct": 2.8,
   "avg_largest_swing_pct": 2.7,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "AMZN",
   "n_days": 13,
   "avg_eff": 0.599,
   "pct_trend": 69.2,
   "pct_chop": 15.4,
   "pct_mixed": 15.4,
   "avg_path_pct": 3.1,
   "avg_range_pct": 2.5,
   "avg_largest_swing_pct": 2.4,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "EBAY",
   "n_days": 8,
   "avg_eff": 0.467,
   "pct_trend": 50.0,
   "pct_chop": 50.0,
   "pct_mixed": 0.0,
   "avg_path_pct": 3.1,
   "avg_range_pct": 2.2,
   "avg_largest_swing_pct": 2.2,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "GOOG",
   "n_days": 15,
   "avg_eff": 0.649,
   "pct_trend": 66.7,
   "pct_chop": 20.0,
   "pct_mixed": 13.3,
   "avg_path_pct": 3.0,
   "avg_range_pct": 2.6,
   "avg_largest_swing_pct": 2.4,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "IBM",
   "n_days": 18,
   "avg_eff": 0.574,
   "pct_trend": 61.1,
   "pct_chop": 11.1,
   "pct_mixed": 27.8,
   "avg_path_pct": 3.0,
   "avg_range_pct": 2.7,
   "avg_largest_swing_pct": 2.4,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "NVDA",
   "n_days": 13,
   "avg_eff": 0.615,
   "pct_trend": 76.9,
   "pct_chop": 23.1,
   "pct_mixed": 0.0,
   "avg_path_pct": 3.0,
   "avg_range_pct": 2.6,
   "avg_largest_swing_pct": 2.4,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "LLY",
   "n_days": 13,
   "avg_eff": 0.485,
   "pct_trend": 46.2,
   "pct_chop": 30.8,
   "pct_mixed": 23.1,
   "avg_path_pct": 2.9,
   "avg_range_pct": 2.2,
   "avg_largest_swing_pct": 2.2,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "BA",
   "n_days": 8,
   "avg_eff": 0.758,
   "pct_trend": 87.5,
   "pct_chop": 12.5,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.9,
   "avg_range_pct": 2.7,
   "avg_largest_swing_pct": 2.7,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "TXT",
   "n_days": 11,
   "avg_eff": 0.609,
   "pct_trend": 81.8,
   "pct_chop": 18.2,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.9,
   "avg_range_pct": 2.7,
   "avg_largest_swing_pct": 2.5,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "MSFT",
   "n_days": 11,
   "avg_eff": 0.795,
   "pct_trend": 90.9,
   "pct_chop": 0.0,
   "pct_mixed": 9.1,
   "avg_path_pct": 2.8,
   "avg_range_pct": 2.7,
   "avg_largest_swing_pct": 2.6,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "NMM",
   "n_days": 12,
   "avg_eff": 0.605,
   "pct_trend": 66.7,
   "pct_chop": 8.3,
   "pct_mixed": 25.0,
   "avg_path_pct": 2.8,
   "avg_range_pct": 2.4,
   "avg_largest_swing_pct": 2.3,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "LHX",
   "n_days": 10,
   "avg_eff": 0.747,
   "pct_trend": 90.0,
   "pct_chop": 10.0,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.6,
   "avg_range_pct": 2.6,
   "avg_largest_swing_pct": 2.4,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "ABNB",
   "n_days": 13,
   "avg_eff": 0.638,
   "pct_trend": 84.6,
   "pct_chop": 15.4,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.4,
   "avg_range_pct": 2.5,
   "avg_largest_swing_pct": 2.1,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "HII",
   "n_days": 8,
   "avg_eff": 0.719,
   "pct_trend": 87.5,
   "pct_chop": 0.0,
   "pct_mixed": 12.5,
   "avg_path_pct": 2.4,
   "avg_range_pct": 2.3,
   "avg_largest_swing_pct": 2.2,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "BABA",
   "n_days": 10,
   "avg_eff": 0.714,
   "pct_trend": 100.0,
   "pct_chop": 0.0,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.1,
   "avg_range_pct": 2.2,
   "avg_largest_swing_pct": 2.1,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "AAPL",
   "n_days": 13,
   "avg_eff": 0.829,
   "pct_trend": 92.3,
   "pct_chop": 0.0,
   "pct_mixed": 7.7,
   "avg_path_pct": 2.0,
   "avg_range_pct": 2.2,
   "avg_largest_swing_pct": 2.0,
   "tradeable_pct": 0.0,
   "character": "QUIET"
  }
 ],
 "failed": [
  "V",
  "JPM",
  "RTX",
  "LMT",
  "GD",
  "NOC",
  "TDG",
  "CVX",
  "AVA",
  "KO"
 ],
 "quiet_floor_path_pct": 8.0
};