window.DAYTYPE_DATA = {
 "built_note": "15m bars, 60d fetch; last 21 sessions = eval window",
 "n": 144,
 "tradeable_path_pct": 10.0,
 "unusual_note": "unusual_pct = % of eval sessions with path >= 1.5x own trailing ~60d median path; separate signal, feeds no label",
 "rows": [
  {
   "ticker": "SNDK",
   "n_days": 21,
   "avg_eff": 0.356,
   "pct_trend": 47.6,
   "pct_chop": 33.3,
   "pct_mixed": 19.0,
   "avg_path_pct": 11.8,
   "avg_range_pct": 5.7,
   "avg_largest_swing_pct": 5.1,
   "tradeable_pct": 52.4,
   "unusual_pct": 14.3,
   "character": "BALANCED"
  },
  {
   "ticker": "BE",
   "n_days": 21,
   "avg_eff": 0.373,
   "pct_trend": 33.3,
   "pct_chop": 23.8,
   "pct_mixed": 42.9,
   "avg_path_pct": 10.3,
   "avg_range_pct": 5.7,
   "avg_largest_swing_pct": 5.5,
   "tradeable_pct": 47.6,
   "unusual_pct": 0.0,
   "character": "BALANCED"
  },
  {
   "ticker": "IREN",
   "n_days": 21,
   "avg_eff": 0.427,
   "pct_trend": 52.4,
   "pct_chop": 33.3,
   "pct_mixed": 14.3,
   "avg_path_pct": 10.1,
   "avg_range_pct": 5.8,
   "avg_largest_swing_pct": 5.4,
   "tradeable_pct": 42.9,
   "unusual_pct": 4.8,
   "character": "BALANCED"
  },
  {
   "ticker": "NBIS",
   "n_days": 21,
   "avg_eff": 0.416,
   "pct_trend": 42.9,
   "pct_chop": 38.1,
   "pct_mixed": 19.0,
   "avg_path_pct": 10.0,
   "avg_range_pct": 6.0,
   "avg_largest_swing_pct": 5.8,
   "tradeable_pct": 42.9,
   "unusual_pct": 0.0,
   "character": "BALANCED"
  },
  {
   "ticker": "CBRS",
   "n_days": 21,
   "avg_eff": 0.367,
   "pct_trend": 42.9,
   "pct_chop": 47.6,
   "pct_mixed": 9.5,
   "avg_path_pct": 9.9,
   "avg_range_pct": 5.2,
   "avg_largest_swing_pct": 4.7,
   "tradeable_pct": 47.6,
   "unusual_pct": 4.8,
   "character": "BALANCED"
  },
  {
   "ticker": "LPTH",
   "n_days": 21,
   "avg_eff": 0.354,
   "pct_trend": 33.3,
   "pct_chop": 42.9,
   "pct_mixed": 23.8,
   "avg_path_pct": 9.4,
   "avg_range_pct": 5.5,
   "avg_largest_swing_pct": 5.2,
   "tradeable_pct": 52.4,
   "unusual_pct": 0.0,
   "character": "BALANCED"
  },
  {
   "ticker": "TSEM",
   "n_days": 21,
   "avg_eff": 0.399,
   "pct_trend": 42.9,
   "pct_chop": 38.1,
   "pct_mixed": 19.0,
   "avg_path_pct": 8.9,
   "avg_range_pct": 5.2,
   "avg_largest_swing_pct": 4.5,
   "tradeable_pct": 33.3,
   "unusual_pct": 14.3,
   "character": "BALANCED"
  },
  {
   "ticker": "ONDS",
   "n_days": 21,
   "avg_eff": 0.382,
   "pct_trend": 42.9,
   "pct_chop": 38.1,
   "pct_mixed": 19.0,
   "avg_path_pct": 8.5,
   "avg_range_pct": 5.1,
   "avg_largest_swing_pct": 4.8,
   "tradeable_pct": 28.6,
   "unusual_pct": 4.8,
   "character": "BALANCED"
  },
  {
   "ticker": "SMCI",
   "n_days": 21,
   "avg_eff": 0.322,
   "pct_trend": 28.6,
   "pct_chop": 42.9,
   "pct_mixed": 28.6,
   "avg_path_pct": 8.3,
   "avg_range_pct": 4.5,
   "avg_largest_swing_pct": 4.3,
   "tradeable_pct": 23.8,
   "unusual_pct": 19.0,
   "character": "BALANCED"
  },
  {
   "ticker": "ARM",
   "n_days": 21,
   "avg_eff": 0.453,
   "pct_trend": 52.4,
   "pct_chop": 28.6,
   "pct_mixed": 19.0,
   "avg_path_pct": 8.3,
   "avg_range_pct": 4.9,
   "avg_largest_swing_pct": 4.5,
   "tradeable_pct": 33.3,
   "unusual_pct": 9.5,
   "character": "TRENDY"
  },
  {
   "ticker": "SMR",
   "n_days": 21,
   "avg_eff": 0.414,
   "pct_trend": 57.1,
   "pct_chop": 28.6,
   "pct_mixed": 14.3,
   "avg_path_pct": 8.3,
   "avg_range_pct": 5.2,
   "avg_largest_swing_pct": 4.9,
   "tradeable_pct": 33.3,
   "unusual_pct": 4.8,
   "character": "BALANCED"
  },
  {
   "ticker": "STX",
   "n_days": 21,
   "avg_eff": 0.33,
   "pct_trend": 38.1,
   "pct_chop": 47.6,
   "pct_mixed": 14.3,
   "avg_path_pct": 8.2,
   "avg_range_pct": 4.6,
   "avg_largest_swing_pct": 4.2,
   "tradeable_pct": 23.8,
   "unusual_pct": 14.3,
   "character": "BALANCED"
  },
  {
   "ticker": "WDC",
   "n_days": 21,
   "avg_eff": 0.297,
   "pct_trend": 23.8,
   "pct_chop": 42.9,
   "pct_mixed": 33.3,
   "avg_path_pct": 8.1,
   "avg_range_pct": 4.5,
   "avg_largest_swing_pct": 4.1,
   "tradeable_pct": 38.1,
   "unusual_pct": 9.5,
   "character": "CHOPPY"
  },
  {
   "ticker": "RGTI",
   "n_days": 21,
   "avg_eff": 0.452,
   "pct_trend": 57.1,
   "pct_chop": 33.3,
   "pct_mixed": 9.5,
   "avg_path_pct": 8.0,
   "avg_range_pct": 4.9,
   "avg_largest_swing_pct": 4.5,
   "tradeable_pct": 28.6,
   "unusual_pct": 4.8,
   "character": "TRENDY"
  },
  {
   "ticker": "CRWV",
   "n_days": 21,
   "avg_eff": 0.52,
   "pct_trend": 47.6,
   "pct_chop": 14.3,
   "pct_mixed": 38.1,
   "avg_path_pct": 7.9,
   "avg_range_pct": 5.0,
   "avg_largest_swing_pct": 4.3,
   "tradeable_pct": 23.8,
   "unusual_pct": 9.5,
   "character": "QUIET"
  },
  {
   "ticker": "INFQ",
   "n_days": 21,
   "avg_eff": 0.45,
   "pct_trend": 42.9,
   "pct_chop": 28.6,
   "pct_mixed": 28.6,
   "avg_path_pct": 7.8,
   "avg_range_pct": 4.9,
   "avg_largest_swing_pct": 4.6,
   "tradeable_pct": 23.8,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "MRVL",
   "n_days": 21,
   "avg_eff": 0.49,
   "pct_trend": 47.6,
   "pct_chop": 28.6,
   "pct_mixed": 23.8,
   "avg_path_pct": 7.7,
   "avg_range_pct": 4.3,
   "avg_largest_swing_pct": 4.0,
   "tradeable_pct": 23.8,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "OKLO",
   "n_days": 21,
   "avg_eff": 0.492,
   "pct_trend": 61.9,
   "pct_chop": 14.3,
   "pct_mixed": 23.8,
   "avg_path_pct": 7.7,
   "avg_range_pct": 5.2,
   "avg_largest_swing_pct": 4.9,
   "tradeable_pct": 19.0,
   "unusual_pct": 14.3,
   "character": "QUIET"
  },
  {
   "ticker": "ASTS",
   "n_days": 21,
   "avg_eff": 0.407,
   "pct_trend": 42.9,
   "pct_chop": 33.3,
   "pct_mixed": 23.8,
   "avg_path_pct": 7.7,
   "avg_range_pct": 4.6,
   "avg_largest_swing_pct": 4.2,
   "tradeable_pct": 33.3,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "PCT",
   "n_days": 21,
   "avg_eff": 0.399,
   "pct_trend": 33.3,
   "pct_chop": 33.3,
   "pct_mixed": 33.3,
   "avg_path_pct": 7.5,
   "avg_range_pct": 4.6,
   "avg_largest_swing_pct": 4.1,
   "tradeable_pct": 28.6,
   "unusual_pct": 19.0,
   "character": "QUIET"
  },
  {
   "ticker": "LASR",
   "n_days": 21,
   "avg_eff": 0.55,
   "pct_trend": 52.4,
   "pct_chop": 19.0,
   "pct_mixed": 28.6,
   "avg_path_pct": 7.5,
   "avg_range_pct": 4.6,
   "avg_largest_swing_pct": 4.3,
   "tradeable_pct": 23.8,
   "unusual_pct": 9.5,
   "character": "QUIET"
  },
  {
   "ticker": "MU",
   "n_days": 21,
   "avg_eff": 0.344,
   "pct_trend": 42.9,
   "pct_chop": 42.9,
   "pct_mixed": 14.3,
   "avg_path_pct": 7.4,
   "avg_range_pct": 4.1,
   "avg_largest_swing_pct": 3.6,
   "tradeable_pct": 19.0,
   "unusual_pct": 9.5,
   "character": "QUIET"
  },
  {
   "ticker": "INOD",
   "n_days": 21,
   "avg_eff": 0.44,
   "pct_trend": 42.9,
   "pct_chop": 33.3,
   "pct_mixed": 23.8,
   "avg_path_pct": 7.2,
   "avg_range_pct": 4.2,
   "avg_largest_swing_pct": 4.0,
   "tradeable_pct": 28.6,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "QBTS",
   "n_days": 21,
   "avg_eff": 0.473,
   "pct_trend": 42.9,
   "pct_chop": 23.8,
   "pct_mixed": 33.3,
   "avg_path_pct": 7.2,
   "avg_range_pct": 4.3,
   "avg_largest_swing_pct": 3.9,
   "tradeable_pct": 19.0,
   "unusual_pct": 9.5,
   "character": "QUIET"
  },
  {
   "ticker": "TER",
   "n_days": 21,
   "avg_eff": 0.428,
   "pct_trend": 38.1,
   "pct_chop": 23.8,
   "pct_mixed": 38.1,
   "avg_path_pct": 7.0,
   "avg_range_pct": 4.0,
   "avg_largest_swing_pct": 3.7,
   "tradeable_pct": 19.0,
   "unusual_pct": 9.5,
   "character": "QUIET"
  },
  {
   "ticker": "IONQ",
   "n_days": 21,
   "avg_eff": 0.429,
   "pct_trend": 42.9,
   "pct_chop": 28.6,
   "pct_mixed": 28.6,
   "avg_path_pct": 7.0,
   "avg_range_pct": 4.1,
   "avg_largest_swing_pct": 3.7,
   "tradeable_pct": 19.0,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "MPWR",
   "n_days": 21,
   "avg_eff": 0.371,
   "pct_trend": 33.3,
   "pct_chop": 52.4,
   "pct_mixed": 14.3,
   "avg_path_pct": 6.7,
   "avg_range_pct": 3.8,
   "avg_largest_swing_pct": 3.6,
   "tradeable_pct": 19.0,
   "unusual_pct": 19.0,
   "character": "QUIET"
  },
  {
   "ticker": "RKLB",
   "n_days": 21,
   "avg_eff": 0.457,
   "pct_trend": 47.6,
   "pct_chop": 38.1,
   "pct_mixed": 14.3,
   "avg_path_pct": 6.7,
   "avg_range_pct": 4.1,
   "avg_largest_swing_pct": 3.6,
   "tradeable_pct": 23.8,
   "unusual_pct": 9.5,
   "character": "QUIET"
  },
  {
   "ticker": "RDDT",
   "n_days": 21,
   "avg_eff": 0.478,
   "pct_trend": 42.9,
   "pct_chop": 28.6,
   "pct_mixed": 28.6,
   "avg_path_pct": 6.6,
   "avg_range_pct": 4.2,
   "avg_largest_swing_pct": 4.0,
   "tradeable_pct": 9.5,
   "unusual_pct": 9.5,
   "character": "QUIET"
  },
  {
   "ticker": "COIN",
   "n_days": 21,
   "avg_eff": 0.404,
   "pct_trend": 47.6,
   "pct_chop": 28.6,
   "pct_mixed": 23.8,
   "avg_path_pct": 6.6,
   "avg_range_pct": 4.2,
   "avg_largest_swing_pct": 3.9,
   "tradeable_pct": 19.0,
   "unusual_pct": 19.0,
   "character": "QUIET"
  },
  {
   "ticker": "SOUN",
   "n_days": 21,
   "avg_eff": 0.487,
   "pct_trend": 61.9,
   "pct_chop": 14.3,
   "pct_mixed": 23.8,
   "avg_path_pct": 6.4,
   "avg_range_pct": 4.4,
   "avg_largest_swing_pct": 3.8,
   "tradeable_pct": 19.0,
   "unusual_pct": 19.0,
   "character": "QUIET"
  },
  {
   "ticker": "HOOD",
   "n_days": 21,
   "avg_eff": 0.474,
   "pct_trend": 57.1,
   "pct_chop": 23.8,
   "pct_mixed": 19.0,
   "avg_path_pct": 6.3,
   "avg_range_pct": 4.0,
   "avg_largest_swing_pct": 3.7,
   "tradeable_pct": 14.3,
   "unusual_pct": 14.3,
   "character": "QUIET"
  },
  {
   "ticker": "AXON",
   "n_days": 21,
   "avg_eff": 0.542,
   "pct_trend": 57.1,
   "pct_chop": 19.0,
   "pct_mixed": 23.8,
   "avg_path_pct": 6.1,
   "avg_range_pct": 4.5,
   "avg_largest_swing_pct": 4.2,
   "tradeable_pct": 14.3,
   "unusual_pct": 28.6,
   "character": "QUIET"
  },
  {
   "ticker": "INTC",
   "n_days": 21,
   "avg_eff": 0.488,
   "pct_trend": 42.9,
   "pct_chop": 33.3,
   "pct_mixed": 23.8,
   "avg_path_pct": 6.0,
   "avg_range_pct": 3.6,
   "avg_largest_swing_pct": 3.5,
   "tradeable_pct": 19.0,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "DELL",
   "n_days": 21,
   "avg_eff": 0.458,
   "pct_trend": 47.6,
   "pct_chop": 23.8,
   "pct_mixed": 28.6,
   "avg_path_pct": 6.0,
   "avg_range_pct": 3.9,
   "avg_largest_swing_pct": 3.7,
   "tradeable_pct": 19.0,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "KLAC",
   "n_days": 21,
   "avg_eff": 0.468,
   "pct_trend": 52.4,
   "pct_chop": 19.0,
   "pct_mixed": 28.6,
   "avg_path_pct": 5.9,
   "avg_range_pct": 3.6,
   "avg_largest_swing_pct": 3.2,
   "tradeable_pct": 9.5,
   "unusual_pct": 14.3,
   "character": "QUIET"
  },
  {
   "ticker": "GFS",
   "n_days": 21,
   "avg_eff": 0.484,
   "pct_trend": 52.4,
   "pct_chop": 14.3,
   "pct_mixed": 33.3,
   "avg_path_pct": 5.9,
   "avg_range_pct": 3.6,
   "avg_largest_swing_pct": 3.5,
   "tradeable_pct": 9.5,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "AVAV",
   "n_days": 21,
   "avg_eff": 0.64,
   "pct_trend": 81.0,
   "pct_chop": 9.5,
   "pct_mixed": 9.5,
   "avg_path_pct": 5.9,
   "avg_range_pct": 4.4,
   "avg_largest_swing_pct": 4.2,
   "tradeable_pct": 14.3,
   "unusual_pct": 14.3,
   "character": "QUIET"
  },
  {
   "ticker": "KTOS",
   "n_days": 21,
   "avg_eff": 0.5,
   "pct_trend": 61.9,
   "pct_chop": 23.8,
   "pct_mixed": 14.3,
   "avg_path_pct": 5.9,
   "avg_range_pct": 4.0,
   "avg_largest_swing_pct": 3.6,
   "tradeable_pct": 9.5,
   "unusual_pct": 9.5,
   "character": "QUIET"
  },
  {
   "ticker": "VRT",
   "n_days": 21,
   "avg_eff": 0.534,
   "pct_trend": 52.4,
   "pct_chop": 23.8,
   "pct_mixed": 23.8,
   "avg_path_pct": 5.9,
   "avg_range_pct": 3.5,
   "avg_largest_swing_pct": 3.3,
   "tradeable_pct": 14.3,
   "unusual_pct": 14.3,
   "character": "QUIET"
  },
  {
   "ticker": "ON",
   "n_days": 21,
   "avg_eff": 0.383,
   "pct_trend": 47.6,
   "pct_chop": 33.3,
   "pct_mixed": 19.0,
   "avg_path_pct": 5.8,
   "avg_range_pct": 3.1,
   "avg_largest_swing_pct": 2.9,
   "tradeable_pct": 14.3,
   "unusual_pct": 9.5,
   "character": "QUIET"
  },
  {
   "ticker": "LRCX",
   "n_days": 21,
   "avg_eff": 0.472,
   "pct_trend": 47.6,
   "pct_chop": 33.3,
   "pct_mixed": 19.0,
   "avg_path_pct": 5.7,
   "avg_range_pct": 3.5,
   "avg_largest_swing_pct": 3.3,
   "tradeable_pct": 9.5,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "MBLY",
   "n_days": 21,
   "avg_eff": 0.538,
   "pct_trend": 57.1,
   "pct_chop": 23.8,
   "pct_mixed": 19.0,
   "avg_path_pct": 5.7,
   "avg_range_pct": 3.9,
   "avg_largest_swing_pct": 3.7,
   "tradeable_pct": 9.5,
   "unusual_pct": 14.3,
   "character": "QUIET"
  },
  {
   "ticker": "GLW",
   "n_days": 21,
   "avg_eff": 0.587,
   "pct_trend": 66.7,
   "pct_chop": 14.3,
   "pct_mixed": 19.0,
   "avg_path_pct": 5.5,
   "avg_range_pct": 3.9,
   "avg_largest_swing_pct": 3.6,
   "tradeable_pct": 9.5,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "HPE",
   "n_days": 21,
   "avg_eff": 0.554,
   "pct_trend": 52.4,
   "pct_chop": 14.3,
   "pct_mixed": 33.3,
   "avg_path_pct": 5.4,
   "avg_range_pct": 3.7,
   "avg_largest_swing_pct": 3.5,
   "tradeable_pct": 9.5,
   "unusual_pct": 19.0,
   "character": "QUIET"
  },
  {
   "ticker": "AMD",
   "n_days": 21,
   "avg_eff": 0.539,
   "pct_trend": 57.1,
   "pct_chop": 23.8,
   "pct_mixed": 19.0,
   "avg_path_pct": 5.4,
   "avg_range_pct": 3.3,
   "avg_largest_swing_pct": 3.1,
   "tradeable_pct": 19.0,
   "unusual_pct": 19.0,
   "character": "QUIET"
  },
  {
   "ticker": "SYM",
   "n_days": 21,
   "avg_eff": 0.572,
   "pct_trend": 66.7,
   "pct_chop": 19.0,
   "pct_mixed": 14.3,
   "avg_path_pct": 5.4,
   "avg_range_pct": 3.9,
   "avg_largest_swing_pct": 3.6,
   "tradeable_pct": 9.5,
   "unusual_pct": 9.5,
   "character": "QUIET"
  },
  {
   "ticker": "AMAT",
   "n_days": 21,
   "avg_eff": 0.49,
   "pct_trend": 61.9,
   "pct_chop": 28.6,
   "pct_mixed": 9.5,
   "avg_path_pct": 5.3,
   "avg_range_pct": 3.3,
   "avg_largest_swing_pct": 2.9,
   "tradeable_pct": 14.3,
   "unusual_pct": 14.3,
   "character": "QUIET"
  },
  {
   "ticker": "CVNA",
   "n_days": 21,
   "avg_eff": 0.522,
   "pct_trend": 57.1,
   "pct_chop": 28.6,
   "pct_mixed": 14.3,
   "avg_path_pct": 5.3,
   "avg_range_pct": 3.8,
   "avg_largest_swing_pct": 3.5,
   "tradeable_pct": 9.5,
   "unusual_pct": 9.5,
   "character": "QUIET"
  },
  {
   "ticker": "ANET",
   "n_days": 21,
   "avg_eff": 0.512,
   "pct_trend": 57.1,
   "pct_chop": 19.0,
   "pct_mixed": 23.8,
   "avg_path_pct": 5.1,
   "avg_range_pct": 3.3,
   "avg_largest_swing_pct": 3.1,
   "tradeable_pct": 9.5,
   "unusual_pct": 9.5,
   "character": "QUIET"
  },
  {
   "ticker": "CTMX",
   "n_days": 21,
   "avg_eff": 0.533,
   "pct_trend": 52.4,
   "pct_chop": 14.3,
   "pct_mixed": 33.3,
   "avg_path_pct": 5.0,
   "avg_range_pct": 3.5,
   "avg_largest_swing_pct": 3.2,
   "tradeable_pct": 4.8,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "Q",
   "n_days": 21,
   "avg_eff": 0.544,
   "pct_trend": 61.9,
   "pct_chop": 28.6,
   "pct_mixed": 9.5,
   "avg_path_pct": 5.0,
   "avg_range_pct": 3.2,
   "avg_largest_swing_pct": 2.9,
   "tradeable_pct": 14.3,
   "unusual_pct": 19.0,
   "character": "QUIET"
  },
  {
   "ticker": "OKTA",
   "n_days": 21,
   "avg_eff": 0.528,
   "pct_trend": 52.4,
   "pct_chop": 14.3,
   "pct_mixed": 33.3,
   "avg_path_pct": 4.9,
   "avg_range_pct": 3.3,
   "avg_largest_swing_pct": 3.2,
   "tradeable_pct": 0.0,
   "unusual_pct": 14.3,
   "character": "QUIET"
  },
  {
   "ticker": "RBLX",
   "n_days": 21,
   "avg_eff": 0.457,
   "pct_trend": 42.9,
   "pct_chop": 42.9,
   "pct_mixed": 14.3,
   "avg_path_pct": 4.8,
   "avg_range_pct": 3.5,
   "avg_largest_swing_pct": 3.2,
   "tradeable_pct": 4.8,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "PLTR",
   "n_days": 21,
   "avg_eff": 0.541,
   "pct_trend": 57.1,
   "pct_chop": 28.6,
   "pct_mixed": 14.3,
   "avg_path_pct": 4.7,
   "avg_range_pct": 3.7,
   "avg_largest_swing_pct": 3.6,
   "tradeable_pct": 0.0,
   "unusual_pct": 19.0,
   "character": "QUIET"
  },
  {
   "ticker": "ORCL",
   "n_days": 21,
   "avg_eff": 0.454,
   "pct_trend": 52.4,
   "pct_chop": 33.3,
   "pct_mixed": 14.3,
   "avg_path_pct": 4.6,
   "avg_range_pct": 3.1,
   "avg_largest_swing_pct": 2.9,
   "tradeable_pct": 0.0,
   "unusual_pct": 23.8,
   "character": "QUIET"
  },
  {
   "ticker": "U",
   "n_days": 21,
   "avg_eff": 0.492,
   "pct_trend": 52.4,
   "pct_chop": 28.6,
   "pct_mixed": 19.0,
   "avg_path_pct": 4.6,
   "avg_range_pct": 3.4,
   "avg_largest_swing_pct": 3.1,
   "tradeable_pct": 4.8,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "MCHP",
   "n_days": 21,
   "avg_eff": 0.606,
   "pct_trend": 71.4,
   "pct_chop": 14.3,
   "pct_mixed": 14.3,
   "avg_path_pct": 4.6,
   "avg_range_pct": 3.2,
   "avg_largest_swing_pct": 3.0,
   "tradeable_pct": 9.5,
   "unusual_pct": 19.0,
   "character": "QUIET"
  },
  {
   "ticker": "MOG-A",
   "n_days": 21,
   "avg_eff": 0.585,
   "pct_trend": 71.4,
   "pct_chop": 19.0,
   "pct_mixed": 9.5,
   "avg_path_pct": 4.5,
   "avg_range_pct": 3.5,
   "avg_largest_swing_pct": 3.3,
   "tradeable_pct": 4.8,
   "unusual_pct": 42.9,
   "character": "QUIET"
  },
  {
   "ticker": "IOT",
   "n_days": 21,
   "avg_eff": 0.626,
   "pct_trend": 71.4,
   "pct_chop": 9.5,
   "pct_mixed": 19.0,
   "avg_path_pct": 4.4,
   "avg_range_pct": 3.6,
   "avg_largest_swing_pct": 3.4,
   "tradeable_pct": 0.0,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "CRWD",
   "n_days": 21,
   "avg_eff": 0.558,
   "pct_trend": 61.9,
   "pct_chop": 28.6,
   "pct_mixed": 9.5,
   "avg_path_pct": 4.3,
   "avg_range_pct": 3.3,
   "avg_largest_swing_pct": 3.1,
   "tradeable_pct": 0.0,
   "unusual_pct": 9.5,
   "character": "QUIET"
  },
  {
   "ticker": "NXPI",
   "n_days": 21,
   "avg_eff": 0.618,
   "pct_trend": 61.9,
   "pct_chop": 19.0,
   "pct_mixed": 19.0,
   "avg_path_pct": 4.3,
   "avg_range_pct": 3.0,
   "avg_largest_swing_pct": 2.8,
   "tradeable_pct": 9.5,
   "unusual_pct": 19.0,
   "character": "QUIET"
  },
  {
   "ticker": "SOFI",
   "n_days": 21,
   "avg_eff": 0.644,
   "pct_trend": 71.4,
   "pct_chop": 9.5,
   "pct_mixed": 19.0,
   "avg_path_pct": 4.2,
   "avg_range_pct": 3.6,
   "avg_largest_swing_pct": 3.3,
   "tradeable_pct": 0.0,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "PKE",
   "n_days": 21,
   "avg_eff": 0.53,
   "pct_trend": 52.4,
   "pct_chop": 23.8,
   "pct_mixed": 23.8,
   "avg_path_pct": 4.2,
   "avg_range_pct": 3.1,
   "avg_largest_swing_pct": 2.8,
   "tradeable_pct": 4.8,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "JBLU",
   "n_days": 21,
   "avg_eff": 0.637,
   "pct_trend": 61.9,
   "pct_chop": 9.5,
   "pct_mixed": 28.6,
   "avg_path_pct": 4.2,
   "avg_range_pct": 3.2,
   "avg_largest_swing_pct": 2.9,
   "tradeable_pct": 4.8,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "KDEF",
   "n_days": 21,
   "avg_eff": 0.527,
   "pct_trend": 61.9,
   "pct_chop": 23.8,
   "pct_mixed": 14.3,
   "avg_path_pct": 4.1,
   "avg_range_pct": 3.0,
   "avg_largest_swing_pct": 2.8,
   "tradeable_pct": 4.8,
   "unusual_pct": 14.3,
   "character": "QUIET"
  },
  {
   "ticker": "PANW",
   "n_days": 21,
   "avg_eff": 0.649,
   "pct_trend": 71.4,
   "pct_chop": 23.8,
   "pct_mixed": 4.8,
   "avg_path_pct": 4.0,
   "avg_range_pct": 3.2,
   "avg_largest_swing_pct": 3.0,
   "tradeable_pct": 0.0,
   "unusual_pct": 23.8,
   "character": "QUIET"
  },
  {
   "ticker": "TSM",
   "n_days": 21,
   "avg_eff": 0.529,
   "pct_trend": 57.1,
   "pct_chop": 23.8,
   "pct_mixed": 19.0,
   "avg_path_pct": 4.0,
   "avg_range_pct": 2.8,
   "avg_largest_swing_pct": 2.6,
   "tradeable_pct": 4.8,
   "unusual_pct": 38.1,
   "character": "QUIET"
  },
  {
   "ticker": "TSLA",
   "n_days": 21,
   "avg_eff": 0.535,
   "pct_trend": 57.1,
   "pct_chop": 14.3,
   "pct_mixed": 28.6,
   "avg_path_pct": 3.9,
   "avg_range_pct": 3.0,
   "avg_largest_swing_pct": 2.8,
   "tradeable_pct": 0.0,
   "unusual_pct": 9.5,
   "character": "QUIET"
  },
  {
   "ticker": "QCOM",
   "n_days": 21,
   "avg_eff": 0.529,
   "pct_trend": 57.1,
   "pct_chop": 23.8,
   "pct_mixed": 19.0,
   "avg_path_pct": 3.9,
   "avg_range_pct": 2.8,
   "avg_largest_swing_pct": 2.7,
   "tradeable_pct": 4.8,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "CGNX",
   "n_days": 21,
   "avg_eff": 0.722,
   "pct_trend": 90.5,
   "pct_chop": 9.5,
   "pct_mixed": 0.0,
   "avg_path_pct": 3.9,
   "avg_range_pct": 3.3,
   "avg_largest_swing_pct": 3.1,
   "tradeable_pct": 4.8,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "CCJ",
   "n_days": 21,
   "avg_eff": 0.518,
   "pct_trend": 52.4,
   "pct_chop": 33.3,
   "pct_mixed": 14.3,
   "avg_path_pct": 3.9,
   "avg_range_pct": 2.9,
   "avg_largest_swing_pct": 2.7,
   "tradeable_pct": 0.0,
   "unusual_pct": 9.5,
   "character": "QUIET"
  },
  {
   "ticker": "SHOP",
   "n_days": 21,
   "avg_eff": 0.671,
   "pct_trend": 81.0,
   "pct_chop": 9.5,
   "pct_mixed": 9.5,
   "avg_path_pct": 3.8,
   "avg_range_pct": 3.0,
   "avg_largest_swing_pct": 2.9,
   "tradeable_pct": 0.0,
   "unusual_pct": 9.5,
   "character": "QUIET"
  },
  {
   "ticker": "IBM",
   "n_days": 21,
   "avg_eff": 0.563,
   "pct_trend": 61.9,
   "pct_chop": 14.3,
   "pct_mixed": 23.8,
   "avg_path_pct": 3.8,
   "avg_range_pct": 3.2,
   "avg_largest_swing_pct": 3.0,
   "tradeable_pct": 0.0,
   "unusual_pct": 38.1,
   "character": "QUIET"
  },
  {
   "ticker": "DASH",
   "n_days": 21,
   "avg_eff": 0.517,
   "pct_trend": 57.1,
   "pct_chop": 28.6,
   "pct_mixed": 14.3,
   "avg_path_pct": 3.8,
   "avg_range_pct": 2.9,
   "avg_largest_swing_pct": 2.6,
   "tradeable_pct": 4.8,
   "unusual_pct": 19.0,
   "character": "QUIET"
  },
  {
   "ticker": "ASML",
   "n_days": 21,
   "avg_eff": 0.531,
   "pct_trend": 57.1,
   "pct_chop": 23.8,
   "pct_mixed": 19.0,
   "avg_path_pct": 3.8,
   "avg_range_pct": 2.8,
   "avg_largest_swing_pct": 2.6,
   "tradeable_pct": 9.5,
   "unusual_pct": 19.0,
   "character": "QUIET"
  },
  {
   "ticker": "SNPS",
   "n_days": 21,
   "avg_eff": 0.744,
   "pct_trend": 85.7,
   "pct_chop": 9.5,
   "pct_mixed": 4.8,
   "avg_path_pct": 3.6,
   "avg_range_pct": 2.8,
   "avg_largest_swing_pct": 2.6,
   "tradeable_pct": 4.8,
   "unusual_pct": 14.3,
   "character": "QUIET"
  },
  {
   "ticker": "HUM",
   "n_days": 21,
   "avg_eff": 0.674,
   "pct_trend": 76.2,
   "pct_chop": 14.3,
   "pct_mixed": 9.5,
   "avg_path_pct": 3.6,
   "avg_range_pct": 2.9,
   "avg_largest_swing_pct": 2.7,
   "tradeable_pct": 9.5,
   "unusual_pct": 23.8,
   "character": "QUIET"
  },
  {
   "ticker": "META",
   "n_days": 21,
   "avg_eff": 0.568,
   "pct_trend": 57.1,
   "pct_chop": 23.8,
   "pct_mixed": 19.0,
   "avg_path_pct": 3.5,
   "avg_range_pct": 2.9,
   "avg_largest_swing_pct": 2.8,
   "tradeable_pct": 0.0,
   "unusual_pct": 28.6,
   "character": "QUIET"
  },
  {
   "ticker": "NICE",
   "n_days": 21,
   "avg_eff": 0.655,
   "pct_trend": 76.2,
   "pct_chop": 14.3,
   "pct_mixed": 9.5,
   "avg_path_pct": 3.5,
   "avg_range_pct": 3.0,
   "avg_largest_swing_pct": 2.9,
   "tradeable_pct": 0.0,
   "unusual_pct": 19.0,
   "character": "QUIET"
  },
  {
   "ticker": "NVDA",
   "n_days": 21,
   "avg_eff": 0.68,
   "pct_trend": 71.4,
   "pct_chop": 9.5,
   "pct_mixed": 19.0,
   "avg_path_pct": 3.5,
   "avg_range_pct": 2.9,
   "avg_largest_swing_pct": 2.7,
   "tradeable_pct": 0.0,
   "unusual_pct": 33.3,
   "character": "QUIET"
  },
  {
   "ticker": "TXN",
   "n_days": 21,
   "avg_eff": 0.46,
   "pct_trend": 47.6,
   "pct_chop": 28.6,
   "pct_mixed": 23.8,
   "avg_path_pct": 3.5,
   "avg_range_pct": 2.5,
   "avg_largest_swing_pct": 2.4,
   "tradeable_pct": 4.8,
   "unusual_pct": 14.3,
   "character": "QUIET"
  },
  {
   "ticker": "CSCO",
   "n_days": 21,
   "avg_eff": 0.547,
   "pct_trend": 61.9,
   "pct_chop": 19.0,
   "pct_mixed": 19.0,
   "avg_path_pct": 3.4,
   "avg_range_pct": 2.7,
   "avg_largest_swing_pct": 2.5,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "AVGO",
   "n_days": 21,
   "avg_eff": 0.57,
   "pct_trend": 71.4,
   "pct_chop": 19.0,
   "pct_mixed": 9.5,
   "avg_path_pct": 3.4,
   "avg_range_pct": 2.9,
   "avg_largest_swing_pct": 2.7,
   "tradeable_pct": 4.8,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "NU",
   "n_days": 21,
   "avg_eff": 0.608,
   "pct_trend": 66.7,
   "pct_chop": 14.3,
   "pct_mixed": 19.0,
   "avg_path_pct": 3.4,
   "avg_range_pct": 2.9,
   "avg_largest_swing_pct": 2.8,
   "tradeable_pct": 0.0,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "MOH",
   "n_days": 21,
   "avg_eff": 0.627,
   "pct_trend": 76.2,
   "pct_chop": 14.3,
   "pct_mixed": 9.5,
   "avg_path_pct": 3.4,
   "avg_range_pct": 2.9,
   "avg_largest_swing_pct": 2.7,
   "tradeable_pct": 9.5,
   "unusual_pct": 9.5,
   "character": "QUIET"
  },
  {
   "ticker": "CAT",
   "n_days": 21,
   "avg_eff": 0.601,
   "pct_trend": 76.2,
   "pct_chop": 19.0,
   "pct_mixed": 4.8,
   "avg_path_pct": 3.4,
   "avg_range_pct": 2.8,
   "avg_largest_swing_pct": 2.7,
   "tradeable_pct": 0.0,
   "unusual_pct": 23.8,
   "character": "QUIET"
  },
  {
   "ticker": "BA",
   "n_days": 21,
   "avg_eff": 0.684,
   "pct_trend": 71.4,
   "pct_chop": 9.5,
   "pct_mixed": 19.0,
   "avg_path_pct": 3.3,
   "avg_range_pct": 2.7,
   "avg_largest_swing_pct": 2.7,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "PINS",
   "n_days": 21,
   "avg_eff": 0.663,
   "pct_trend": 71.4,
   "pct_chop": 9.5,
   "pct_mixed": 19.0,
   "avg_path_pct": 3.2,
   "avg_range_pct": 2.9,
   "avg_largest_swing_pct": 2.6,
   "tradeable_pct": 0.0,
   "unusual_pct": 4.8,
   "character": "QUIET"
  },
  {
   "ticker": "ADI",
   "n_days": 21,
   "avg_eff": 0.564,
   "pct_trend": 61.9,
   "pct_chop": 23.8,
   "pct_mixed": 14.3,
   "avg_path_pct": 3.2,
   "avg_range_pct": 2.4,
   "avg_largest_swing_pct": 2.3,
   "tradeable_pct": 4.8,
   "unusual_pct": 23.8,
   "character": "QUIET"
  },
  {
   "ticker": "XYZ",
   "n_days": 21,
   "avg_eff": 0.619,
   "pct_trend": 81.0,
   "pct_chop": 4.8,
   "pct_mixed": 14.3,
   "avg_path_pct": 3.2,
   "avg_range_pct": 2.8,
   "avg_largest_swing_pct": 2.6,
   "tradeable_pct": 4.8,
   "unusual_pct": 9.5,
   "character": "QUIET"
  },
  {
   "ticker": "CEG",
   "n_days": 21,
   "avg_eff": 0.627,
   "pct_trend": 76.2,
   "pct_chop": 14.3,
   "pct_mixed": 9.5,
   "avg_path_pct": 3.2,
   "avg_range_pct": 2.6,
   "avg_largest_swing_pct": 2.4,
   "tradeable_pct": 0.0,
   "unusual_pct": 23.8,
   "character": "QUIET"
  },
  {
   "ticker": "HII",
   "n_days": 21,
   "avg_eff": 0.642,
   "pct_trend": 71.4,
   "pct_chop": 9.5,
   "pct_mixed": 19.0,
   "avg_path_pct": 3.1,
   "avg_range_pct": 2.9,
   "avg_largest_swing_pct": 2.6,
   "tradeable_pct": 4.8,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "HWM",
   "n_days": 21,
   "avg_eff": 0.728,
   "pct_trend": 90.5,
   "pct_chop": 4.8,
   "pct_mixed": 4.8,
   "avg_path_pct": 3.1,
   "avg_range_pct": 2.8,
   "avg_largest_swing_pct": 2.5,
   "tradeable_pct": 0.0,
   "unusual_pct": 14.3,
   "character": "QUIET"
  },
  {
   "ticker": "TXT",
   "n_days": 21,
   "avg_eff": 0.648,
   "pct_trend": 81.0,
   "pct_chop": 14.3,
   "pct_mixed": 4.8,
   "avg_path_pct": 3.1,
   "avg_range_pct": 2.5,
   "avg_largest_swing_pct": 2.3,
   "tradeable_pct": 4.8,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "AAL",
   "n_days": 21,
   "avg_eff": 0.667,
   "pct_trend": 71.4,
   "pct_chop": 14.3,
   "pct_mixed": 14.3,
   "avg_path_pct": 3.1,
   "avg_range_pct": 2.8,
   "avg_largest_swing_pct": 2.5,
   "tradeable_pct": 0.0,
   "unusual_pct": 14.3,
   "character": "QUIET"
  },
  {
   "ticker": "NQ=F",
   "n_days": 16,
   "avg_eff": 0.702,
   "pct_trend": 75.0,
   "pct_chop": 6.2,
   "pct_mixed": 18.8,
   "avg_path_pct": 3.1,
   "avg_range_pct": 2.7,
   "avg_largest_swing_pct": 2.4,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "VZ",
   "n_days": 21,
   "avg_eff": 0.637,
   "pct_trend": 71.4,
   "pct_chop": 19.0,
   "pct_mixed": 9.5,
   "avg_path_pct": 3.1,
   "avg_range_pct": 2.4,
   "avg_largest_swing_pct": 2.4,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "EBAY",
   "n_days": 21,
   "avg_eff": 0.747,
   "pct_trend": 81.0,
   "pct_chop": 14.3,
   "pct_mixed": 4.8,
   "avg_path_pct": 3.0,
   "avg_range_pct": 2.5,
   "avg_largest_swing_pct": 2.5,
   "tradeable_pct": 0.0,
   "unusual_pct": 9.5,
   "character": "QUIET"
  },
  {
   "ticker": "NMM",
   "n_days": 21,
   "avg_eff": 0.675,
   "pct_trend": 71.4,
   "pct_chop": 4.8,
   "pct_mixed": 23.8,
   "avg_path_pct": 3.0,
   "avg_range_pct": 2.7,
   "avg_largest_swing_pct": 2.6,
   "tradeable_pct": 0.0,
   "unusual_pct": 33.3,
   "character": "QUIET"
  },
  {
   "ticker": "MSFT",
   "n_days": 21,
   "avg_eff": 0.687,
   "pct_trend": 76.2,
   "pct_chop": 9.5,
   "pct_mixed": 14.3,
   "avg_path_pct": 2.9,
   "avg_range_pct": 2.7,
   "avg_largest_swing_pct": 2.5,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "HEI",
   "n_days": 21,
   "avg_eff": 0.619,
   "pct_trend": 81.0,
   "pct_chop": 9.5,
   "pct_mixed": 9.5,
   "avg_path_pct": 2.9,
   "avg_range_pct": 2.5,
   "avg_largest_swing_pct": 2.4,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "AVA",
   "n_days": 10,
   "avg_eff": 0.684,
   "pct_trend": 80.0,
   "pct_chop": 10.0,
   "pct_mixed": 10.0,
   "avg_path_pct": 2.9,
   "avg_range_pct": 2.4,
   "avg_largest_swing_pct": 2.4,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "GM",
   "n_days": 21,
   "avg_eff": 0.623,
   "pct_trend": 66.7,
   "pct_chop": 23.8,
   "pct_mixed": 9.5,
   "avg_path_pct": 2.9,
   "avg_range_pct": 2.6,
   "avg_largest_swing_pct": 2.4,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "T",
   "n_days": 21,
   "avg_eff": 0.701,
   "pct_trend": 81.0,
   "pct_chop": 4.8,
   "pct_mixed": 14.3,
   "avg_path_pct": 2.9,
   "avg_range_pct": 2.8,
   "avg_largest_swing_pct": 2.6,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "GOOG",
   "n_days": 21,
   "avg_eff": 0.712,
   "pct_trend": 81.0,
   "pct_chop": 19.0,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.8,
   "avg_range_pct": 2.6,
   "avg_largest_swing_pct": 2.5,
   "tradeable_pct": 0.0,
   "unusual_pct": 19.0,
   "character": "QUIET"
  },
  {
   "ticker": "AMZN",
   "n_days": 21,
   "avg_eff": 0.659,
   "pct_trend": 66.7,
   "pct_chop": 9.5,
   "pct_mixed": 23.8,
   "avg_path_pct": 2.8,
   "avg_range_pct": 2.4,
   "avg_largest_swing_pct": 2.3,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "LLY",
   "n_days": 21,
   "avg_eff": 0.538,
   "pct_trend": 47.6,
   "pct_chop": 23.8,
   "pct_mixed": 28.6,
   "avg_path_pct": 2.8,
   "avg_range_pct": 2.2,
   "avg_largest_swing_pct": 2.1,
   "tradeable_pct": 0.0,
   "unusual_pct": 19.0,
   "character": "QUIET"
  },
  {
   "ticker": "LHX",
   "n_days": 21,
   "avg_eff": 0.705,
   "pct_trend": 81.0,
   "pct_chop": 14.3,
   "pct_mixed": 4.8,
   "avg_path_pct": 2.8,
   "avg_range_pct": 2.5,
   "avg_largest_swing_pct": 2.4,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "GE",
   "n_days": 21,
   "avg_eff": 0.701,
   "pct_trend": 76.2,
   "pct_chop": 9.5,
   "pct_mixed": 14.3,
   "avg_path_pct": 2.8,
   "avg_range_pct": 2.5,
   "avg_largest_swing_pct": 2.4,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "GS",
   "n_days": 21,
   "avg_eff": 0.658,
   "pct_trend": 76.2,
   "pct_chop": 4.8,
   "pct_mixed": 19.0,
   "avg_path_pct": 2.8,
   "avg_range_pct": 2.4,
   "avg_largest_swing_pct": 2.2,
   "tradeable_pct": 0.0,
   "unusual_pct": 9.5,
   "character": "QUIET"
  },
  {
   "ticker": "MS",
   "n_days": 18,
   "avg_eff": 0.729,
   "pct_trend": 83.3,
   "pct_chop": 0.0,
   "pct_mixed": 16.7,
   "avg_path_pct": 2.8,
   "avg_range_pct": 2.5,
   "avg_largest_swing_pct": 2.4,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "UNH",
   "n_days": 16,
   "avg_eff": 0.717,
   "pct_trend": 87.5,
   "pct_chop": 6.2,
   "pct_mixed": 6.2,
   "avg_path_pct": 2.7,
   "avg_range_pct": 2.4,
   "avg_largest_swing_pct": 2.3,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "TDG",
   "n_days": 19,
   "avg_eff": 0.821,
   "pct_trend": 89.5,
   "pct_chop": 10.5,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.6,
   "avg_range_pct": 2.6,
   "avg_largest_swing_pct": 2.4,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "HD",
   "n_days": 14,
   "avg_eff": 0.786,
   "pct_trend": 85.7,
   "pct_chop": 14.3,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.6,
   "avg_range_pct": 2.4,
   "avg_largest_swing_pct": 2.4,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "HON",
   "n_days": 21,
   "avg_eff": 0.655,
   "pct_trend": 76.2,
   "pct_chop": 9.5,
   "pct_mixed": 14.3,
   "avg_path_pct": 2.6,
   "avg_range_pct": 2.4,
   "avg_largest_swing_pct": 2.2,
   "tradeable_pct": 0.0,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "MRK",
   "n_days": 21,
   "avg_eff": 0.66,
   "pct_trend": 76.2,
   "pct_chop": 19.0,
   "pct_mixed": 4.8,
   "avg_path_pct": 2.6,
   "avg_range_pct": 2.2,
   "avg_largest_swing_pct": 2.1,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "NFLX",
   "n_days": 21,
   "avg_eff": 0.758,
   "pct_trend": 85.7,
   "pct_chop": 4.8,
   "pct_mixed": 9.5,
   "avg_path_pct": 2.5,
   "avg_range_pct": 2.5,
   "avg_largest_swing_pct": 2.3,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "ABNB",
   "n_days": 21,
   "avg_eff": 0.667,
   "pct_trend": 76.2,
   "pct_chop": 9.5,
   "pct_mixed": 14.3,
   "avg_path_pct": 2.5,
   "avg_range_pct": 2.3,
   "avg_largest_swing_pct": 2.3,
   "tradeable_pct": 0.0,
   "unusual_pct": 19.0,
   "character": "QUIET"
  },
  {
   "ticker": "BABA",
   "n_days": 21,
   "avg_eff": 0.74,
   "pct_trend": 95.2,
   "pct_chop": 4.8,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.5,
   "avg_range_pct": 2.5,
   "avg_largest_swing_pct": 2.4,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "NKE",
   "n_days": 21,
   "avg_eff": 0.702,
   "pct_trend": 85.7,
   "pct_chop": 9.5,
   "pct_mixed": 4.8,
   "avg_path_pct": 2.4,
   "avg_range_pct": 2.4,
   "avg_largest_swing_pct": 2.3,
   "tradeable_pct": 0.0,
   "unusual_pct": 0.0,
   "character": "QUIET"
  },
  {
   "ticker": "KO",
   "n_days": 11,
   "avg_eff": 0.75,
   "pct_trend": 81.8,
   "pct_chop": 9.1,
   "pct_mixed": 9.1,
   "avg_path_pct": 2.4,
   "avg_range_pct": 2.4,
   "avg_largest_swing_pct": 2.3,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "RTX",
   "n_days": 17,
   "avg_eff": 0.722,
   "pct_trend": 82.4,
   "pct_chop": 11.8,
   "pct_mixed": 5.9,
   "avg_path_pct": 2.3,
   "avg_range_pct": 2.2,
   "avg_largest_swing_pct": 2.1,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "NOC",
   "n_days": 21,
   "avg_eff": 0.823,
   "pct_trend": 90.5,
   "pct_chop": 4.8,
   "pct_mixed": 4.8,
   "avg_path_pct": 2.3,
   "avg_range_pct": 2.5,
   "avg_largest_swing_pct": 2.2,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "SCHW",
   "n_days": 16,
   "avg_eff": 0.753,
   "pct_trend": 93.8,
   "pct_chop": 6.2,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.3,
   "avg_range_pct": 2.4,
   "avg_largest_swing_pct": 2.2,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "LMT",
   "n_days": 21,
   "avg_eff": 0.857,
   "pct_trend": 95.2,
   "pct_chop": 4.8,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.2,
   "avg_range_pct": 2.3,
   "avg_largest_swing_pct": 2.1,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "CVX",
   "n_days": 10,
   "avg_eff": 0.752,
   "pct_trend": 80.0,
   "pct_chop": 10.0,
   "pct_mixed": 10.0,
   "avg_path_pct": 2.2,
   "avg_range_pct": 2.1,
   "avg_largest_swing_pct": 2.0,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "CVS",
   "n_days": 21,
   "avg_eff": 0.75,
   "pct_trend": 90.5,
   "pct_chop": 9.5,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.2,
   "avg_range_pct": 2.2,
   "avg_largest_swing_pct": 2.0,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "MO",
   "n_days": 17,
   "avg_eff": 0.796,
   "pct_trend": 94.1,
   "pct_chop": 5.9,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.2,
   "avg_range_pct": 2.2,
   "avg_largest_swing_pct": 2.0,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "PEP",
   "n_days": 12,
   "avg_eff": 0.81,
   "pct_trend": 100.0,
   "pct_chop": 0.0,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.2,
   "avg_range_pct": 2.4,
   "avg_largest_swing_pct": 2.2,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "PG",
   "n_days": 8,
   "avg_eff": 0.829,
   "pct_trend": 100.0,
   "pct_chop": 0.0,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.2,
   "avg_range_pct": 2.3,
   "avg_largest_swing_pct": 2.2,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "UNP",
   "n_days": 17,
   "avg_eff": 0.77,
   "pct_trend": 94.1,
   "pct_chop": 5.9,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.2,
   "avg_range_pct": 2.2,
   "avg_largest_swing_pct": 2.1,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "JPM",
   "n_days": 13,
   "avg_eff": 0.72,
   "pct_trend": 84.6,
   "pct_chop": 15.4,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.1,
   "avg_range_pct": 2.0,
   "avg_largest_swing_pct": 2.0,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "ABBV",
   "n_days": 16,
   "avg_eff": 0.785,
   "pct_trend": 93.8,
   "pct_chop": 0.0,
   "pct_mixed": 6.2,
   "avg_path_pct": 2.1,
   "avg_range_pct": 2.2,
   "avg_largest_swing_pct": 2.1,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "JNJ",
   "n_days": 10,
   "avg_eff": 0.839,
   "pct_trend": 100.0,
   "pct_chop": 0.0,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.1,
   "avg_range_pct": 2.2,
   "avg_largest_swing_pct": 2.1,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "LIN",
   "n_days": 9,
   "avg_eff": 0.885,
   "pct_trend": 100.0,
   "pct_chop": 0.0,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.1,
   "avg_range_pct": 2.2,
   "avg_largest_swing_pct": 2.1,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "WFC",
   "n_days": 17,
   "avg_eff": 0.791,
   "pct_trend": 82.4,
   "pct_chop": 0.0,
   "pct_mixed": 17.6,
   "avg_path_pct": 2.1,
   "avg_range_pct": 2.3,
   "avg_largest_swing_pct": 2.2,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "XOM",
   "n_days": 11,
   "avg_eff": 0.675,
   "pct_trend": 72.7,
   "pct_chop": 9.1,
   "pct_mixed": 18.2,
   "avg_path_pct": 2.1,
   "avg_range_pct": 2.1,
   "avg_largest_swing_pct": 2.0,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "AAPL",
   "n_days": 21,
   "avg_eff": 0.837,
   "pct_trend": 100.0,
   "pct_chop": 0.0,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.0,
   "avg_range_pct": 2.0,
   "avg_largest_swing_pct": 2.0,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "GD",
   "n_days": 14,
   "avg_eff": 0.727,
   "pct_trend": 92.9,
   "pct_chop": 0.0,
   "pct_mixed": 7.1,
   "avg_path_pct": 2.0,
   "avg_range_pct": 2.2,
   "avg_largest_swing_pct": 2.0,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "COST",
   "n_days": 8,
   "avg_eff": 0.77,
   "pct_trend": 87.5,
   "pct_chop": 0.0,
   "pct_mixed": 12.5,
   "avg_path_pct": 2.0,
   "avg_range_pct": 2.2,
   "avg_largest_swing_pct": 2.0,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "WMT",
   "n_days": 18,
   "avg_eff": 0.814,
   "pct_trend": 94.4,
   "pct_chop": 5.6,
   "pct_mixed": 0.0,
   "avg_path_pct": 2.0,
   "avg_range_pct": 2.1,
   "avg_largest_swing_pct": 1.9,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "V",
   "n_days": 12,
   "avg_eff": 0.702,
   "pct_trend": 75.0,
   "pct_chop": 0.0,
   "pct_mixed": 25.0,
   "avg_path_pct": 1.9,
   "avg_range_pct": 2.0,
   "avg_largest_swing_pct": 1.9,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  },
  {
   "ticker": "BAC",
   "n_days": 10,
   "avg_eff": 0.851,
   "pct_trend": 90.0,
   "pct_chop": 0.0,
   "pct_mixed": 10.0,
   "avg_path_pct": 1.8,
   "avg_range_pct": 1.8,
   "avg_largest_swing_pct": 1.8,
   "tradeable_pct": 0.0,
   "unusual_pct": null,
   "character": "QUIET"
  }
 ],
 "failed": [
  "SPCX",
  "ES=F",
  "BRK-B"
 ]
};
